### PR TITLE
Juke = True ; to Juke = False ; 

### PR DESCRIPTION
**Pull request by UltraSirius**
Just In Case, I Already DO This in My MinionPlayer.js,

### CODE REVIEW

**Comment by Megabyte918** [comment]
why?

**Comment by NatsuTheGreat** [comment]
I just feel like closin' this

**Comment by Agarian** [comment]
Perhaps thats what causes the bugged movement with minions

**Comment by NatsuTheGreat** [comment]
No.... That's what decides weather to split away from the enemy (juke away from the enemy)

**Comment by GhostShot3** [comment]
why this change

**Pull request closed without merging**
