### PR TITLE
The Eject Virus Update

### PR DESCRIPTION
**Pull request by Andrews54757**
```
+ ejected virus option to enable ejected virus not mass
+ ejected viruses have their owners color
+ Ejected viruses will not pop the owner (same with op viruses)
- Removed virus gamemode
- reverted lots of changes from #176 as it made the game really laggy
```

### CODE REVIEW

**Comment by Andrews54757** [comment]
any ajs dev can do it @AJS-development/ogar-unlimited-devs

**Comment by Andrews54757** [comment]
by that i mean push it

**Comment by NatsuTheGreat** [comment]
How do I become a dev?

**Comment by Andrews54757** [comment]
If you make lots of good contributions

**Comment by Andrews54757** [comment]
Whatever, il push it

**Pull request merged**
