### PR TITLE
Massive update / Joining the project

### PR DESCRIPTION
**Pull request by MichaelLeeHobbs**
Gratings, 
My boys love agario and I am answering you call for: I need a person who can code who organizes and formats my code (it is pretty messy)

This pull request is 100% functionally the same. It only address formatting/syntax issues. There are a couple of minor code optimizations but they only optimize the syntax to reduce loc and improve readability. One I finish with an initial review I will start tackling the bigger issues.

### CODE REVIEW

**Comment by Lukkez** [comment]
Tested? no bugs?

**Comment by Agarian** [comment]
shall i merge?

**Comment by Agarian** [comment]
and i would personally like to say welcome to the ogar unlimited dev team!

**Comment by MichaelLeeHobbs** [comment]
There are no bugs that I am aware of and I have done basic testing. That said it was not extensively tested but nothing I did should have resulted in bugs.

**Comment by Agarian** [comment]
ok im gonna merge if any problems occur, make another pull that fixes it or we need to revert.

**Comment by Andrews54757** [comment]
@MichaelLeeHobbs Thank you very much. On behalf of the AJS dev team I thank you.
Andrew s 
Creator of ogar unlimited

**Comment by Andrews54757** [comment]
@MichaelLeeHobbs There is an error with the bots #180 and the getbiggest function overwrites the getbiggest function in playertracker

**Comment by Andrews54757** [comment]
nvm about the overwrite

**Comment by Agarian** [comment]
lol #fails

**Pull request merged**
