### PR TITLE
Fixing bot skins

### PR DESCRIPTION
**Pull request by GhostShot3**
Finding wrong links

- [x] Ready to merge

Then type this afterwards "I have read and agreed to the contributing guidelines"

### CODE REVIEW

**Comment by Megabyte918** [comment]
Line 31 in botnames.txt should be "european_union" not "european_onion"
Line 85 in botnames.txt should be "satanist" not "stanist"

**Comment by GhostShot3** [comment]
@Megabyte918 Thank you

**Comment by GhostShot3** [comment]
ops is blangadesh is right

**Comment by GhostShot3** [comment]
finished.

**Pull request merged**
