### PR TITLE
Splitpopping now works!

### PR DESCRIPTION
**Pull request by Megabyte918**
I do NOT take credit for this whatsoever. It was all @retslac and his coding that made this possible. He was unable to make a request so he allowed me to do it for him <3

### CODE REVIEW

**Comment by firelightning13** [comment]
retslac saves the day :D

**Comment by ItzLevvie** [comment]
Duplicate functions of ````if (check.cellType == 0) {...)```

**Comment by Megabyte918** [comment]
@ItzLevvie what would that do and how do i do it xD

**Comment by firelightning13** [comment]
@ItzLevvie It means double checking

**Comment by ItzLevvie** [comment]
@Megabyte918 Just remove the line above 1414.

**Comment by firelightning13** [comment]
Ok i see that

**Comment by StormGS5** [comment]
yeah just got to wait for andrews to read this comment and todays my birthday i expect atleast one of the updates iv been waiting for for a while

**Comment by Andrews54757** [comment]
@Megabyte918  needs to do what @ItzLevvie  says and I can't code as I am on vacation

**Comment by Megabyte918** [comment]
I get an error when i do that

**Comment by ItzLevvie** [comment]
Remove this
```

       // if we're deleting from this.nodesPlayer, fix outer loop variables; we need to update its length, and maybe 'i' too
       if (check.cellType == 0) {
         len--;
         if (check.nodeId < cell.nodeId) {
            i--;
          }
        
```

**Comment by Megabyte918** [comment]
Ohh alright. Ill do it when i get home from school. Sorry other programmers that are reading this I know its probably painful on to see how much of a noob I am >. <

**Comment by firelightning13** [comment]
@Megabyte918 Not just u :P

**Comment by retslac** [comment]
@Megabyte918 No worries, you'll get it fixed! :)

**Pull request merged**
