### PR TITLE
Real virius popping mechanics

### PR DESCRIPTION
**Pull request by StormGS5**
can you update virius popping to allow popsplit if u dont know what that is look here

https://www.youtube.com/watch?v=Zp4WZiGs8bs

### CODE REVIEW

**Comment by Agarian** [comment]
idk what to do about that...

**Comment by StormGS5** [comment]
oh :(

**Comment by StormGS5** [comment]
just compare the popping on a virius on real agar.io and the one on the server and see what u can do about that please i was trying to popsplit someone on my server and failed and i got ate and i felt like a noob

**Comment by Agarian** [comment]
ill give it a shot

**Comment by StormGS5** [comment]
ok thanks

**Pull request closed without merging**
