### PR TITLE
multiple updates (no more commits will be added to this pull.) y u no merge?

### PR DESCRIPTION
**Pull request by Agarian**

### CODE REVIEW

**Comment by Agarian** [comment]
I noticed your announcement Andrews so no need to say anything.

**Comment by Agarian** [comment]
i may close it...

**Comment by Andrews54757** [comment]
Ignore all checks have failed, it is a glitch with travis

**Comment by Agarian** [comment]
ik

**Comment by Agarian** [comment]
i heard the news

**Comment by Agarian** [comment]
will u start merge again?

**Pull request merged**
