### PR TITLE
A WHOLE NEW GAMEMODE...EXPERIMENTAL v2!

### PR DESCRIPTION
**Pull request by Agarian**
THIS GAMEMODE ADDS MOVING VIRUSES, STICKY (A.K.A. leech) CELLS AND MORE!
PLEASE REPORT ANY ERRORS

### CODE REVIEW

**Comment by Andrews54757** [comment]
What are all the features of this gamemode? BTW THIS IS AWESOME!!!

**Comment by Andrews54757** [comment]
(also, i dont know how it works, ogarserv doesnt explain)

**Comment by Agarian** [comment]
There is a beacon 
Not really with purpose currently...

**Comment by Andrews54757** [comment]
I figured it out

**Comment by Agarian** [comment]
So what u think?

**Comment by Agarian** [comment]
Ive had this in my build for a looong time

**Comment by Andrews54757** [comment]
It awesome(except still some physics i dont know i will ask jaralowel)

**Comment by NatsuTheGreat** [comment]
Scholtes made all of this. Gotta admit he made some good codes.

**Comment by Agarian** [comment]
Ikr

**Comment by NatsuTheGreat** [comment]
I like the sticky the cell.

**Comment by Agarian** [comment]
i tried to make it pushable by ejected mass like viruses in the original experimental

**Comment by NatsuTheGreat** [comment]
Oh lol, Did you succeed?

**Comment by Agarian** [comment]
i said "didnt work"

**Comment by NatsuTheGreat** [comment]
lol

**Pull request merged**
