### PR TITLE
Big Update

### PR DESCRIPTION
**Pull request by Andrews54757**
BIG UPDATE SLATED FOR SATURDAY, MAR 5. (The Suggestions Update or The Update That Changed Agario)

(Done) Spawnmass command to change spawnmass for different players
(Done) Freeze command
(Done) Smart bot despawn/spawn
(Done) Speed command
(Done) Realistic names config
(Done) Max mass suggestion
(Done) Better update command
(Done) Banrange
(Done) Better anti bot measures (Easy Verify)
(Done) Range
(Done) Periodical Commands
(Done) Other things

Some details

Max mass suggestion allows you to exceed mass limit for a second 

Smart bot spawn despawn makes amount of server bots vary on the amount of players

Update command now has the botnames and skins option to only download certain files

Better anti bot measures adds a verify config at game server.ini If one, players have to verify that they are not a bot by typing a 3 digit (random) code. If failed over 5 times, they would be kicked.

Range command allows you do use for example the name command at batch. do `range 1 10 name lol` changes players 1 through 10s names to lol

periodical commands allow you to run commands periodically

### CODE REVIEW

**Comment by Andrews54757** [comment]
TO THE OTHER AJS DEVS, DO NOT MERGE YET

**Comment by StormGS5** [comment]
can do speed command

**Comment by StormGS5** [comment]
can  u add it?

**Comment by Andrews54757** [comment]
I did

**Comment by StormGS5** [comment]
if u did i would know it so i updated # THREE TIMES AND STILL NO SPEED OR STARTMASS BY IP IN CONSOLE!

**Comment by Andrews54757** [comment]
Because i didn't update yet. this is a pull request. i will update on staurday. (are you new to github?)

**Comment by StormGS5** [comment]
@Andrews54757 why cant u update the files u **ALREADY COMPLETED GENIUS**

**Comment by StormGS5** [comment]
yes im good at git hub and i feel so small cuz everone becides me knows how to code only that i can type in coding is return str; var and item position ()

**Comment by Andrews54757** [comment]
> @Andrews54757 why cant u update the files u ALREADY COMPLETED GENIUS

Well, it because i want to test for bugs and i may add more features AND PLS BE NICE

**Comment by StormGS5** [comment]
@Andrews54757 sorry i get mad sometimes i got mental issues

**Comment by Andrews54757** [comment]
Its okay,

**Comment by StormGS5** [comment]
:)

**Comment by Andrews54757** [comment]
TO THE OTHER AJS DEVS, DO NOT MERGE YET

**Comment by StormGS5** [comment]
ok

**Comment by StormGS5** [comment]
please update

**Comment by Agarian** [comment]
lol i leave to Michigan when this happens

**Comment by hassanila97** [comment]
Great work @Andrews54757 I see that you have some typos here and there but I will fix them when the update is merged :)   Also we need a better readme as the current one is not formatted well

**Comment by Andrews54757** [comment]
I need someone to test out every single feature of this update so i can launch with confidence

**Comment by firelightning13** [comment]
I would like to test the bot despawn since i suggested it

**Comment by Andrews54757** [comment]
I think i fixed

**Comment by Agarian** [comment]
whered all the other messages go?
-----------------------------------------------
were they deleted?

**Comment by Agarian** [comment]
CANT WAIT TO MERGE THIS (ive been given the honors to do so, thanx andrews!)

**Comment by Agarian** [comment]
Just 3 hours left. Please let me know if you need more time to add commits by 10 pm

**Comment by hassanila97** [comment]
Ehi cant you also fix the freeze behaviour that we get in Agar.io when mouse pointer is in center? We dont get it in Ogar :(    Hope sm1 can explain better what I mean

**Comment by Agarian** [comment]
In agar.io, when you keep your mouse at the center of the screen, and then split, your cell does not go back to the center. Instead the cell dtops in place.

**Comment by hassanila97** [comment]
@Agarian thank you for explaining....  Also the same thing happens when you get shoot with a virus and your mouse is at center...  You get split by the vrus but they dont go back to the ceter like @Agarian said

**Comment by Agarian** [comment]
stormGS5 recently posted: 
storm
he then later deleted the comment.

**Comment by firelightning13** [comment]
You know I just left this for 12 hours what is going on?

Sorry my time zone is different,and right now its already Saturday 9:36 AM lol

**Comment by Lukkez** [comment]
It's 10:36 Pm here, you will open at 00:00 at my country LOL

**Comment by Agarian** [comment]
its 8:40 PM and by 10 PM i get to merge this :smiley:

**Comment by Lukkez** [comment]
I live on Brazil =P

**Comment by Agarian** [comment]
:O

**Comment by firelightning13** [comment]
I'm so excited to see the **BIG UPDATE**! :DDDD by the time in 11 AM(in my timezone)

**Comment by Lukkez** [comment]
@firelightning13 Me too

**Comment by Agarian** [comment]
Playin MC to pass the time

**Comment by Agarian** [comment]
issues are back bros

**Comment by Agarian** [comment]
@Andrews54757 you should add 2 more commits to make 100 lol

**Comment by Agarian** [comment]
10 pm time to merge!

**Comment by Agarian** [comment]
Have Made my way to Tennessee so, half way to my destination!

**Pull request merged**
