### PR TITLE
More Realistic Skins Idea by Azerox

### PR DESCRIPTION
**Pull request by AgarAzerox**
@Andrews54757 
I have an idea to make Ogar more realistic as agar.io.
As we know, if you equip a skin your **cell color** change depending on the skin and we can see only skin **border**.
Then my ideia is to fix a cell right color to each skin.
Example:

> _**Shark skin**_ we can see that your cell color is a dark blue in agar.io in 
R,G,B = ("0,44,108") HTML = ("002C6C")

Then basically will be like this:

> `{"cellColor":"0x002C6C00","gameplayId":100,"image":"Shark.png","productId":"skin_shark","skinType":"veteran"}`

Waiting a answer!
Carefully Agar Azerox.

> Contact me by e-mail if you prefer: ("**_agarazerox1407@gmail.com_**")

"I have read and agreed to the contributing guidelines"

### CODE REVIEW

**Comment by LegitSoulja** [comment]
This isn't needed..

**Comment by AgarAzerox** [comment]
But can you give me a code to do it on my ogar?
I really want this, i put all the new skins on my server, updated the realistic names, i only need the code to keep a cell color to a skin and where i can put this code to keep skin color.
I understand that this is not necessary for you, but to it is necessary, please help. I only need it to my Ogar be perfect. Thanks for the attention.

**Comment by LegitSoulja** [comment]
Why don't you code a way to get a color from an image? It's not hard.

**Comment by AgarAzerox** [comment]
Because I'm not a programmer and do not understand about it and I have no idea which modify file.

**Comment by LegitSoulja** [comment]
Stay connected to the forums http://forum.ogarul.io

I'll discuss about modding servers

**Comment by AgarAzerox** [comment]
Ok.

**Pull request closed without merging**
