### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by Megabyte918**
Sorry i've been dead
- Changed playerspeed back to 30 (already done nvm)
- Added sRestoreTicks config for splitting collision
- Reverted autoSplitSpeed back to 350 (480 was too fast)
- Increased virus amount on map (10 and 50 were too little)
- Added 50% chance of cells switching order (100 switched too much)
- Added autoSplitSpeed config
- Switched some other configs between files and created a "physics" section
- Increased vRestoreTicks config, makes it so you can somewhat tricksplit through viruses (might - have to edit virus explosions later on)
- Fixed teleporting when doing virus throws (lazy fix)
- Re-added playerBotGrowEnabled config
- Reverted to older splitversion (basically same physics)
- Added splitMult config (only works with splitversion set to 0)
- Changed some settings to vanilla 
- Added w's from Ogar, as they are more realistic
- Added splitDistance and wDistance configs, for more customizable physics

I will work on fixing pushback, splitspeedand, and making more vanilla-like virus explosions next time

Sorry for the spam of commits lol 

I have read and agreed to the contributing guidelines

### CODE REVIEW

**Comment by Agarian** [comment]
I really wish i could play ogarUL :(

**Comment by Megabyte918** [comment]
damn these checks take forever

**Comment by Agarian** [comment]
Has conflicts.

**Comment by Megabyte918** [comment]
I can't merge it myself, GitHub desktop has errors on my computer

**Comment by Andrews54757** [comment]
il merge it

**Comment by Andrews54757** [comment]
I know command line. lol

**Pull request merged**
