### PR TITLE
Quadrants: Trying to solve lag

### PR DESCRIPTION
**Pull request by Andrews54757**
This is probably going to take a while.

#### What is this?
This PR is trying to split the map into quadrants. The idea is quite simple. Although all the nodes will be stored in a "unified" world, they would be divided into 4 quadrants. It is all about efficiency. Instead of doing all these collision checks and etc on all nodes in the map, It will "skip" over the ones that are not in the cells quadrant. 

#### Whats done
1. Quadrants implemented into ejected mass loops
2. implemented in mothercells
3. implemented in Beacons
4. implemented in other loops
5. Special implement in players visible nodes
6. Added a tutorial.
7. also added language support.

#### Whats the difference?
Here, I will show you. 

screen shot 2016-06-18 at 10 04 29 am
This is when my "player" is inside a quadrant. there is a loop that usually loops through ALL the nodes on the map to see whether it is visible to me or not. But, with the quadrant, it only loops through the nodes on the quadrant. This is the format of the name `quadrant:pID - nodes count` As you can see, the nodes count is small compared to the picture below.

screen shot 2016-06-18 at 10 04 39 am

This is when it is outside of a quadrant. To make it so nodes are not invisible at the boundaries of the quadrant, there is a system where if the player's view box touches the boundaries, it will loop through all the nodes on the map like before. (otherwise, nodes will be invisible until you enter their quadrant). So this is how many nodes it has to go through without quadrants.

### CODE REVIEW

**Comment by twigario** [comment]
Pleez i need a dev JS for my agario private server! if interested add me skype:boteur-creator-99

**Comment by Agarian** [comment]
Ooo this seems interesting

**Comment by Megabyte918** [comment]
gr8 idea

**Comment by fayizan** [comment]
Really I appreciate this new idea,hope ogarul will be much better than Agar..!!

**Comment by Agarian** [comment]
Done already?

**Comment by Agarian** [comment]
F*CK MY ANDROID AND ITS SMALL SCREENNNNNN

**Comment by David1ali12** [comment]
is this merged ?

**Comment by firelightning13** [comment]
Lol dude calm down i use android too

**Pull request merged**
