### PR TITLE
Neat-ified things :)

### PR DESCRIPTION
**Pull request by Megabyte918**
Moved certain configs and created there own sections

### CODE REVIEW

**Comment by Andrews54757** [comment]
Thank you!!!!!!

**Comment by Megabyte918** [comment]
@Andrews54757 np, and just a quick question, how do i use botsmaxsplit? if i set it to 8 does that mean that the bots will split until their in the max? or they WONT split into more than 8 pieces?

**Comment by Andrews54757** [comment]
they wont split if they are over or is on the max amount of cells

**Comment by firelightning13** [comment]
@Megabyte918 noice

**Pull request merged**
