### PR TITLE
Fix issues.

### PR DESCRIPTION
**Pull request by NatsuTheGreat**
This resolves some of #268 .

### CODE REVIEW

**Comment by NatsuTheGreat** [comment]
IF THIS BRINGS ANY BUGS, REPORT PLEASE.

**Comment by Agarian** [comment]
is there a branch i can download? i don't wanna waste time copying and pasting code xD

**Comment by NatsuTheGreat** [comment]
Yeah hang on, Mega needs something from me.

**Comment by Agarian** [comment]
alright

**Comment by NatsuTheGreat** [comment]
https://github.com/NatsuTheGreat/Ogar-unlimited/tree/patch-33 Here you can download that.

**Comment by Agarian** [comment]
cool

**Comment by Agarian** [comment]
i kinda liked the old splitting better, the log10 polyfill was for the bigger cells

**Comment by NatsuTheGreat** [comment]
Do you want it back?

**Comment by Agarian** [comment]
if u want, btw max mass works great! and ejected mass is alot smoother!

**Comment by NatsuTheGreat** [comment]
Does it ruin the big splits?

**Comment by Agarian** [comment]
u mean removing the polyfill?

**Comment by NatsuTheGreat** [comment]
Yeah, I just tested it with 20k mass and it was awesome.

**Comment by Agarian** [comment]
what?

**Comment by NatsuTheGreat** [comment]
The splitting was MUCH MUCH better.

**Comment by Agarian** [comment]
for max mass or after your changes to the cell splitting

**Comment by NatsuTheGreat** [comment]
Cell splitting.

**Comment by Agarian** [comment]
i guess its just me

**Comment by Agarian** [comment]
my server is open http://agar.io/?ip=ogarserverupdate-agarian.c9users.io

**Comment by Andrews54757** [comment]
Yeah, about the auto split function, I forgot to add it in, well, I guess that is done

**Comment by Andrews54757** [comment]
It would be nice if it used the polydill if it was over a certain size

**Comment by Andrews54757** [comment]
Fps is basically gamespeed. Increase it, and you have a faster game

**Comment by NatsuTheGreat** [comment]
The whole split functions seems to be doing well, if poly is really needed, i'll add it back. The splitting WAS satisfying to me, with all sizes.

**Comment by Andrews54757** [comment]
well, it was added here #58

**Comment by Andrews54757** [comment]
i think it would be best if you add it back in

**Comment by Andrews54757** [comment]
nvm

**Comment by NatsuTheGreat** [comment]
Kk

**Comment by Agarian** [comment]
damn i actually liked the polyfill

**Comment by NatsuTheGreat** [comment]
if it is that needed I'll add it back geez xD

**Comment by Agarian** [comment]
WAIT ILL GIVE IT A CHANCE LOL

**Comment by NatsuTheGreat** [comment]
K lol, I just fixed the mothercell issue.

**Comment by Agarian** [comment]
noicd :D also keep your changes to splitting.

**Comment by NatsuTheGreat** [comment]
K, so no need for polyfill?

**Comment by Agarian** [comment]
fk the polyfill lol

**Comment by NatsuTheGreat** [comment]
LOL XD

**Comment by Agarian** [comment]
ikr btw server open WATCH OUT 4 MY CLAN XD http://agar.io/?ip=ogarserverupdate-agarian.c9users.io

**Comment by NatsuTheGreat** [comment]
Racist af...

**Comment by Agarian** [comment]
TF?

**Comment by Agarian** [comment]
oh hitler?

**Comment by NatsuTheGreat** [comment]
yeah..

**Comment by Agarian** [comment]
i saw andrews 54757

**Comment by NatsuTheGreat** [comment]
I don't like hitler..

**Comment by Agarian** [comment]
not anymore =\

**Comment by Agarian** [comment]
im hellcat @Andrews54757

**Comment by NatsuTheGreat** [comment]
what is your clan chat?

**Comment by Agarian** [comment]
https://discord.gg/0nZOvpw372EDCuMV

**Comment by Agarian** [comment]
i have a ghost cell issue on my server sometimes when removing minions

**Comment by NatsuTheGreat** [comment]
I'll look into it.

And that's a pretty darn big clan!

**Comment by NatsuTheGreat** [comment]
Tell me how it happens, so I can get a better visual of what's causing it.

**Comment by Agarian** [comment]
so i do minion [playerID] on myself to remove minions, but some do not get removed, they cant eat anything or anyone, but others can eat them

**Comment by NatsuTheGreat** [comment]
What size are the minions?

**Comment by Agarian** [comment]
some were bigger 20K-3K, one was small about 43 mass
not the first time

**Comment by Megabyte918** [comment]
@Agarian u mind if I join discord chat too? Im bored af xP

**Comment by Agarian** [comment]
go ahead

**Comment by Megabyte918** [comment]
The autosplit thingy and smoother ejecting doesnt work :(

**Comment by Agarian** [comment]
Autosplit works fine

**Pull request merged**
