### PR TITLE
Improves README.md

### PR DESCRIPTION
**Pull request by firelightning13**
Basically improves README.md (makes it easy to read, i hope :/ ). This is for #1006 
How would it looks like? You can see it [here](https://github.com/firelightning13/Ogar-unlimited/blob/master/README.md)
What I improved so far...
- Introduction:
 - [x] Adds a link to play.ogarul.tk and edit some description
- Installation Guide (short):
 - [x] Add links to NodeJS site *(version 5.9.0)* and play.ogarul.tk
 - [x] Add some descriptions *(basically windows installation)*
 - [x] Delete a note about Install Dependencies issue *(we don't need it :/)*
- Troubleshooting:
 - [x] Add a link to FAQ and How to Tutorial *(made by Andrew)*
- Highlight features:
 - [x] Typo fix
 - [x] Re-format and add descriptions
 - [x] Add links and updates information
 - [x] *Skins info*: Needs to separate into another section
 - [x] Delete ~~some~~ *(actually) one* of the *not really highlighted anymore* features
 - [x] Re-arrange the list (see which is the most hyped features)
- Notes and plugin section:
 - [x] Don't disturb Andrew's note
 - [x] Letter case and punctuation improvements
 - [x] Edit some info and divides into another sections
- Multiverse:
 - [x] Re-format
- Easy Verify:
 - [x] Typo fix and edit some description
 - [x] Adds *(anti bot measure)* next to the title
- Minions:
 - [x] Re-format *(using tables)*
 - [x] Separates some of the information between agar.io and play.ogarul.tk
- OP:
 - [x] Re-format and re-write all descriptions
- Skins list (and custom skin):
 - [x] Includes info about skin list in custom skin section
 - [x] Separates some of the information between agar.io and play.ogarul.tk and also typo fix
- Obtaining and Using (and Configuring OgarUL section):
 - [x] Update some information
 - [x] The "Configuring OgarUL section" should be put somewhere else
 - [x] This should be put after Inst. Guide (short)
 - [x] Adds a link to OgarUL-NoClient 
- Custom Game Modes:
 - [x] Add/Edit some missing information and some grammar errors
 - [x] Removed/Add some of the game modes
- Chat commands and console commands:
 - [x] Alphabetize*(re-arrange)* list of commands *(so it's easy to look up certain commands)*
 - [x] Typo and duplicate commands fix, edit some info
 - [x] Remove "available"*(deprecated)* and add "killall"
- Contributing and "Things that I dont want you to copy":
 - [x] Letter case fixes*(because why not?)*

-
 - [x] Adds "Table of Contents" section *(used for shortcut link, no need to scroll down)*
 - [x] Add some Markdown flavor to readme *(because its delicious)*
 - [x] Re-arrange all sections:
 - [x] Final check before merge
 - [x] Ready to merge

I have read and agreed to the contributing guidelines

### CODE REVIEW

**Comment by firelightning13** [comment]
This is how the arrangement of sections looks like(currently):

intro
installation guide short
troubleshooting
hightlighted features
andrews note
dont buy ogarUL
dont get other sources
get plugin
other plugin
multiverse
easy verify
minions
op
obtain n using
configure
custom game mode
chat commands
console commands
contributing
things dont want to copy
anything else blablabla

**Comment by Agarian** [comment]
You should remove the `Zombie Team` and `No Collision Zombie Team` gamemodes from the list, as those gamemodes don't exist anymore :(

**Comment by firelightning13** [comment]
@Agarian Ok, got it

**Comment by GhostShot3** [comment]
@firelightning13 You need to update branch

**Comment by fayizan** [comment]
Node version 6.3.1 is compatible with ogarul and working better..!!!

**Comment by Agarian** [comment]
How better?

**Comment by firelightning13** [comment]
@fayizan No errors?

**Comment by fayizan** [comment]
Bug I found Superminion works like normal Minion command,can't set starting mass

**Comment by GhostShot3** [comment]
@fayizan How to run with statitics and how with node 6.3.1 ?

**Comment by SharkFinPro** [comment]
@fayizan It should work...it works for me

**Comment by fayizan** [comment]
@SharkFinPro which works good..?

**Comment by firelightning13** [comment]
Can you guys do me a favor? Because I need to check everything in README.md but I'm very busy at the moment. You could find any typo errors, grammar errors, etc (any features need to add?). You can do pull request (if you want) in my fork here: https://github.com/firelightning13/Ogar-unlimited/pulls

Or you could suggest what to improved in README.md right here

**Comment by Megabyte918** [comment]
Looks good to me.

**Comment by GhostShot3** [comment]
@firelightning13 
xfcxc
Update description
dfddf

**Comment by ItzLevvie** [comment]
" @SharkFinPro which works good..? " - @fayizan

The latest NodeJS version should work alot better than the old / legacy versions as the latest version always has some optimisations.

**Comment by Agarian** [comment]
@firelightning13 Merge time? I'll take it as a yes since "Ready to merge" is checked.

**Comment by Megabyte918** [comment]
@firelightning13 great job =D

**Comment by NatsuTheGreat** [comment]
@firelightning13 Thanks for your contributing. README looks so much neater. :)

**Comment by firelightning13** [comment]
You're welcome guys :)

**Comment by Agarian** [comment]
@firelightning13 #1365

**Pull request merged**
