### PR TITLE
i said i did not want to take a break!(don't  merge)

### PR DESCRIPTION
**Pull request by Agarian**
Even some other devs said that...

### CODE REVIEW

**Comment by Andrews54757** [comment]
You need one. You have been online for hours.

**Comment by raphyjb** [comment]
lol andrew xD U need break too Andrew!

**Comment by ErikParacelsus** [comment]
What happened to issues???

**Comment by raphyjb** [comment]
There no more issues to complain about :D FUCK ME FOR A WEEK WATT EMM I GANNNA DOOOO?!?!?! Im lost, brb ill go hang myself

**Comment by Agarian** [comment]
@ErikParacelsus Andrews terminated them for a week because he thought we needed a "break" :disappointed:

**Comment by Agarian** [comment]
now this is the only place to collab...

**Comment by Agarian** [comment]
Perhaps 𝙸 should delete my account.

**Comment by ErikParacelsus** [comment]
Golee fudge

**Comment by David1ali12** [comment]
Even forum.ogarul.tk :anguished:

**Comment by Andrews54757** [comment]
Please, Have a break. Enough with internet chatting. Do something good with your life. Make real friends, not internet friends.

**Comment by Andrews54757** [comment]
You may code though.

**Comment by Agarian** [comment]
omfg i give up on github

**Comment by Agarian** [comment]
Worst day ever

**Comment by Andrews54757** [comment]
btw I cracked skins
screenshot from 2016-05-31 20-23-16

**Comment by Andrews54757** [comment]
Youl have to wait until saturday

**Comment by Andrews54757** [comment]
Another example:

screenshot from 2016-05-31 20-29-35

**Comment by Andrews54757** [comment]
Next up: Border colors

**Comment by LegitSoulja** [comment]
@AJS-development/ogar-unlimited-devs 

Besides Andrew 

Would you like to work on a new project?

**Comment by Andrews54757** [comment]
let me guess. Lproject

**Comment by Agarian** [comment]
HOLY SH*T ANDREWS FINALLY DID IT :D

**Comment by Agarian** [comment]
Wait, will this work on play.ogarul.tk?

**Comment by Agarian** [comment]
@LegitSoulja probably not

**Comment by David1ali12** [comment]
skins are easy but cant  use in tag so we cant use it with names :(  cell border cant be removed with smooth render

**Comment by Andrews54757** [comment]
@David1ali12 Your 100% wrong It is not easy, and you can use tags like before

**Comment by LegitSoulja** [comment]
@Andrew54757 NOO no LProject lol. Something new. Slither?

**Comment by David1ali12** [comment]
it works with tag  that cool oh ye you are right not easy with tag
and the problem is not with border its with cavas blob 
change 
`ib = ["_canvas'blob"];`
to this 
`ib = [ '_canvas\'blob' ];`

I fixed mind that way. lol

**Comment by raphyjb** [comment]
why the heck cant i port forward my server anymore fuckkkkckckckckkck :(

**Comment by Andrews54757** [comment]
@LegitSoulja I am splitting up the project. As about 50% said they want the normal client, I made another version that works with the normal one. I will merge them together one day so it supports both without any configurations. I made the other one here and you can be in charge of it. https://github.com/AJS-development/Ogar-unlimited-Noclient

**Comment by David1ali12** [comment]
@Andrews54757  everyone wanted the normal client because of skins , no sense for agar.io client anymore it will be just a wast of time .

**Comment by Agarian** [comment]
True

**Comment by Nic0x** [comment]
will spectacle mode works on play.ogarul.tk ?
if skins, spectacle mode etc work with new update on play.ogarul.tk, keep working on this

**Comment by Agarian** [comment]
@Andrews54757 the spectate button in the client is constantly disabled.

**Comment by raphyjb** [comment]
why i keep seeing my name up in PRO TIP!
 ProTip! Notify someone on an issue with a mention, like: @raphyjb

**Comment by Megabyte918** [comment]
I didn't need a break either... im barely online... now i can't see any if the issues or help anyone this SUCKS

**Comment by raphyjb** [comment]
Yo mega u know how to run server on linus?

**Comment by ViinKz** [comment]
please help why when i spawn 600k and the food is 60k ?? i cant change it
please anyone ;-;

**Comment by Andrews54757** [comment]
I also finished advanced multiverse. Servers are now listed in the gamemode select box

**Comment by Nic0x** [comment]
@Andrews54757 Please, for the new update, add new feature, if we press w continually, it feeds fast

**Comment by ErikParacelsus** [comment]
@Nic0x That feature is on config.ini hint hint: w cool down

**Comment by raphyjb** [comment]
@ErikParacelsus no its not. he means having a macro on w

**Comment by jrgryph** [comment]
If you use chrome... you can already zoom.  Hold down control and use your mouse wheel. I find %50 is a good zoom level.

**Comment by Agarian** [comment]
i already mada a macro
(for tampermonkey)

**Comment by Andrews54757** [comment]
I dont support macros

**Comment by Andrews54757** [comment]
im closing this

**Pull request closed without merging**
