### PR TITLE
No more issues?

### PR DESCRIPTION
**Pull request by Lukkez**
I was like wtf, i click on notifications and appear a 404 screen!

### CODE REVIEW

**Comment by Lukkez** [comment]
Don't accept pull request

**Comment by Megabyte918** [comment]
It all started with a skin request....

**Comment by ErikParacelsus** [comment]
rip issues

**Comment by Lukkez** [comment]
The nazi... NAZI IS NOT A GOOD SKIN

**Comment by Lukkez** [comment]
The worst skin

**Comment by Andrews54757** [comment]
it is because people were being disrespectful

**Comment by Andrews54757** [comment]
Proverbs 12:18

The words of the reckless pierce like swords,
but the tongue of the wise brings healing.

**Comment by Agarian** [comment]
dude how could u?

**Comment by Andrews54757** [comment]
@Agarian Do you want to do the honors and press the merge button on the big update pr at 10:00 today?

**Comment by Andrews54757** [comment]
and i disabled issues tempararily, im gonna open back up after update. I just want people to chill

**Comment by Megabyte918** [comment]
@Andrews54757 at LEAST make a pull request where we can post issues with the new big update before it gets released

**Comment by Lukkez** [comment]
I want to press =O but at this time on my timezone it's 17:11 (5:11 PM)

**Comment by Andrews54757** [comment]
Exactly, so issues will be back up when I launch the update

**Comment by Agarian** [comment]
@Andrews54757 YES

**Comment by Agarian** [comment]
10 pm?

**Comment by Agarian** [comment]
note I'll be leaving to Michigan for 2 weeks on saturday (march 5)

**Comment by Agarian** [comment]
lol respond

**Comment by Andrews54757** [comment]
what time is it for you now

**Comment by Agarian** [comment]
5:01 PM

**Comment by Andrews54757** [comment]
Good

**Comment by Agarian** [comment]
i cannot stay up later than 11:30 pm FYI

**Comment by Agarian** [comment]
also the PR still says will be merged on Saturday March 5th

**Comment by Megabyte918** [comment]
Congrats m8

**Comment by Agarian** [comment]
# ISSUES HAVE RETURNED

**Pull request closed without merging**
