### PR TITLE
Physics and stuff

### PR DESCRIPTION
**Pull request by Megabyte918**
- adjusted eating range
- reduced decay rate
- cleaned up start function in GameServer
- add w's from ogar
- minified some code in physics.js, playercell.js, virus.js, cell.js
- removed some unnecessary configs and updated some to match the new splitting
- fixed annoying op bug that prevents you from splitting after you have recombined, as long as you already have that is :)
- added linesplits (angles from multiogar)
- better virus explosions when big/small (mostly big), new explosions allow for same-size popsplits (works best with over 10k mass)
- Added a fix that removes people from the leaderboard if they have disconnected
- Cells now surpass playerMaxMass for a split second before autosplitting like in vanilla
- added player speed formula from ogar
- Added splitting from ogar, with a few tweaks :)
the splitting is alot snappier and similar to vanilla now, and there should be no more pushback (yay!)

Tested and everything works fine! If you have any issues or bugs with this please report it here so I can take a look :)

### CODE REVIEW

**Comment by NatsuTheGreat** [comment]
A ton of this is coming from other sources :/

**Comment by Megabyte918** [comment]
We do updates from Ogar all the time, this project is forked from it afterall

**Comment by NatsuTheGreat** [comment]
What about MultiOgar?

**Comment by Megabyte918** [comment]
I was originally going to use Ogar's splitting angles, because it uses the angleTo function in vector which allows for vertical AND horizontal linesplits, depending on where your mouse is. But implementing that did not go so well, as you remember :/ so i used multiogar's splitting angles because it was the next best thing to having working linesplits in ogarul, it doesn't allow for vertical ones, but it'll have to do for now until i can figure out how to get it working.

**Comment by Megabyte918** [comment]
I was originally going to use Ogar's splitting angles, because it uses the angleTo function in vector which allows for vertical AND horizontal linesplits, depending on where your mouse is. But implementing that did not go so well, as you remember :/ so i used multiogar's splitting angles because it was the next best thing to having working linesplits in ogarul, it doesn't allow for vertical ones, but it'll have to do for now until i can figure out how to get it working.

**Comment by Tyler3D** [comment]
Since you are working on the splits, can you add ogar's original splits from ogar plus, etc.

**Comment by Tyler3D** [comment]
As an Config.

**Comment by Tyler3D** [comment]
Also did you fix popsplits like in your fork?

**Comment by Megabyte918** [comment]
@Tyler3D If you want ogar's original splits replace the current calcMove function with theirs, Im not trying to add any extra configs right now as we already have way too much unnecessary ones that im trying to get rid of :/ 

And what do you mean by "fix popsplits?" if you mean the cells dissapearing bug, that was fixed a while ago in #1325

**Comment by Agarian** [comment]
We should **SERIOUSLY** wait until #1196 is merged!

**Comment by Agarian** [comment]
So for now, i'll do this.

**Comment by Megabyte918** [comment]
I don't think It will be any time soon :/

**Comment by Agarian** [comment]
Whats https://github.com/AJS-development/Ogar-unlimited/pull/1368/commits/c4e39343714e43f4cd665136c426688dfbcd2d85 for?

**Comment by Megabyte918** [comment]
it fixes a small bug that causes you to grow infinitely when you use op or the merge command when merging cells that equal to over playerMaxMass

**Comment by Tyler3D** [comment]
@Megabyte918 No I mean by normal popsplits, so that you can autopopsplit and popsplit huge. I remember someone mentaining to fix this change the virus mult to 2 instead of 3.33 which fixs it but makes virus poping weird. And how could I change the calcmove function. Im not much of a node.js programmer.

**Comment by Agarian** [comment]
@Megabyte918 you needed help on discord?

**Comment by Megabyte918** [comment]
@Agarian nevermind, I got it.
and @Tyler3D didn't you read the changes? lol

> better virus explosions when big/small (mostly big), new explosions allow for same-size popsplits (works best with over 10k mass)
I'll give you the calcMove function soon just hold on till i get back on my phone

**Comment by Tyler3D** [comment]
OK thank you I will try this. And for the popsplit on your fork I can popsplit people bigger than me lol. Is this a big. A very cool bug

**Comment by Tyler3D** [comment]
And also what happened after using ogar's splitting angles for vertical and horizontal linesplis

**Comment by Megabyte918** [comment]
@Tyler3D How much bigger were they? I couldn't seem to reproduce it. And with the angles, there was just a small bug that and I couldn't fix that's all

**Comment by mrzack506** [comment]
Linesplits don't work on your fork @Megabyte918

**Comment by Megabyte918** [comment]
Ima close this until its actually ready

**Comment by Agarian** [comment]
That would be a good idea lol, you available 4 discord?

**Comment by Megabyte918** [comment]
yeah

**Comment by Agarian** [comment]
@Megabyte918 i cannot get the Client plugin to work, i always get the message "Upgrade required" -_-
 i feel as though it is broken

**Comment by Megabyte918** [comment]
You need to provide a client lol, you cant just play it from the direct link

**Comment by Megabyte918** [comment]
@Agarian you must not have your ports set up in the right way, come on discord and i'll help you set it up the way i did mine

**Comment by Agarian** [comment]
Can't, I'm not supposed to even be awake right now

**Comment by GhostShot3** [comment]
@Megabyte918 Why closed this

**Comment by Agarian** [comment]
@Megabyte918 I can now 
(watch him take too long)

**Comment by Megabyte918** [comment]
Im on my phone until tomorrow m8, at a friends house sorry xP

**Comment by Agarian** [comment]
@Megabyte918 I'm available again

**Pull request closed without merging**
