### PR TITLE
Slightly better splitting

### PR DESCRIPTION
**Pull request by Megabyte918**
Made splitting slightly more realistic and similar to vanilla agar

### CODE REVIEW

**Comment by ErikParacelsus** [comment]
Great job!

**Comment by Agarian** [comment]
**COLLISION BEFORE**:
collisionb4
**COLLISION NOW**:
collisionnow
see the difference?

**Comment by Agarian** [comment]
the collision before was better cause smaller cells didn't get squished together ad shown in the **COLLISION NOW** photo

**Comment by Andrews54757** [comment]
Should i revert?

**Comment by Agarian** [comment]
Idk 😓

**Comment by Luka967** [comment]
Double collision per 50ms tends to solve this issue.

**Comment by Agarian** [comment]
i'd prefer the previous collision type. i mean this was what we were trying to avoid was cell squishing.

**Comment by Agarian** [comment]
so it would probably be better to revert.

**Comment by Andrews54757** [comment]
Done

**Comment by Andrews54757** [comment]
Actually, i made it so it is configed. at default it is set to this. but if you dont want it, switch splitversion to 0

**Pull request merged**
