### PR TITLE
Fix #1177 and typo

### LINKED ISSUE #1177: mega split not working!
Hi, 

we used to use 
`playerRecombineTime : -1000
`
on ogar to make the server support very fast split as this video :
https://www.youtube.com/watch?v=6mmhgg0FOT0

when i tried ogar-unlimited its has an issue which is when i reach about 500 score i cannot split :)
its like i merge before i split,

so any help about this ?

### PR DESCRIPTION
**Pull request by Megabyte918**
Lazy fix for #1177, there's probably an easier way of doing it but whatever
And had to fix that typo in randomSkins cause it was bugging the crap out of me =P

I have read and agreed to the contributing guidelines

### CODE REVIEW

**Comment by Agarian** [comment]
guess ill merge it

**Comment by Agarian** [comment]
actually this seems to have broken "Megasplit"

**Comment by Agarian** [comment]
it worked just fine b4

**Comment by Agarian** [comment]
should i revert this?

**Comment by Megabyte918** [comment]
@Agarian It works fine for me, dark mode was with a recombine time of 0 and light mode was with -1000
megasplit

**Comment by AlexandriteErikParacelsus** [comment]
@Megabyte918 w8 how do you doesn't get banned on c9

**Comment by firelightning13** [comment]
@AlexandriteErikParacelsus You can ask c9 support to unban you, you just need to proof that you are coding or testing with OgarUL, not for hosting server.

**Comment by LegitSoulja** [comment]
@firelightning13 even if you are coding, or testing, you will still be banned if you aren't a contributor to ogarul. I suggest not to even bother there time trying. There services isn't really capable of running ogarul servers. I recommend you getting proper hosting.

**Comment by Agarian** [comment]
I actually was able to add a `gamemodes` command which lists all gamemodes. I wil make a PR on it soon

**Comment by SharkFinPro** [comment]
I have A website, can i host a server from there?

**Comment by LegitSoulja** [comment]
@SharkFinPro You can host a client, but not a server.

**Comment by SharkFinPro** [comment]
ok
how would i host a client, without the client files :D

**Comment by LegitSoulja** [comment]
Why would you ask when you can easily obtain it?

**Comment by NatsuTheGreat** [comment]
>how would i host a client, without the client files :D

Wait, what?!

**Comment by SharkFinPro** [comment]
How can i obtain them? i have been looking everywhere....

**Comment by LegitSoulja** [comment]
@SharkFinPro You aren't looking good enough. You should really learn how to use filters :/

**Comment by LegitSoulja** [comment]
https://github.com/AJS-development/Ogar-unlimited/issues/918#issuecomment-225019348

**Comment by Megabyte918** [comment]
Just realized the typo says "premiun" instead of "premium" how tf did i miss that

**Pull request merged**
