### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by firelightning13**
How did I never notice this?! xD

### CODE REVIEW

**Comment by Megabyte918** [comment]
I would have never noticed lol

**Comment by MichaelLeeHobbs** [comment]
Haha I saw this the other day but just ignored it for now. :D

**Comment by firelightning13** [comment]
My brains exploded

**Comment by ItzLevvie** [comment]
http://www.urbandictionary.com/define.php?term=recieve <== @Andrews54757 xD

**Comment by Andrews54757** [comment]
it is for emergencies such as a version being too unstable or it containg sensistive data so i can fix the problem directly i dont need to fix the type as i would probably never use it

**Pull request closed without merging**
