### PR TITLE
Make it more reader-friendly

### PR DESCRIPTION
**Pull request by firelightning13**
If there is something wrong with my grammar or wrong facts, you are welcomed to fix it.

### CODE REVIEW

**Comment by firelightning13** [comment]
I've notice that the lines was way too long :/

**Comment by Agarian** [comment]
Anymore typo fixes?

**Comment by firelightning13** [comment]
Wait

**Comment by Agarian** [comment]
Line 17 "dont" should be "don't" (missing apostrophe ' )

**Comment by Agarian** [comment]
Line 80 maybe remove "I like teaming :)"? LoL

**Comment by Agarian** [comment]
Let me know when to merge

**Comment by firelightning13** [comment]
If i put apostrophe all text will color blue when editing

Github editor is stupid

**Comment by Agarian** [comment]
Shouldnt matter if its a comment line. So, yes go ahead
Also the github editor can be an a**hole sometimes lel

**Comment by Agarian** [comment]
Im going 2 bed its midnight xD

**Comment by firelightning13** [comment]
Lol ok goodnight (late 5 hours)

**Pull request merged**
