### PR TITLE
Lots of updates

### PR DESCRIPTION
**Pull request by NatsuTheGreat**

### CODE REVIEW

**Comment by Andrews54757** [comment]
Please test this (test everything please) so I can merge it (For big updates, there is a large margin of error)

**Comment by NatsuTheGreat** [comment]
It was mainly format lol

**Comment by NatsuTheGreat** [comment]
Everything seems to work fine

**Comment by Andrews54757** [comment]
What about the virus off mode

**Comment by NatsuTheGreat** [comment]
just made it so you spawn from viruses

**Comment by Andrews54757** [comment]
but there is no viruses in virus mode

**Comment by NatsuTheGreat** [comment]
what do you mean

you have the bush viruses

**Comment by Andrews54757** [comment]
The mode where you shoot viruses is virus.js

**Comment by NatsuTheGreat** [comment]
oh, then just take out the virusoff commit

**Comment by Andrews54757** [comment]
Virus mode and virus off mode are different things. Virus mode. = shoot virus, Virus off mode = no viruses

**Comment by Andrews54757** [comment]
Lol

**Comment by NatsuTheGreat** [comment]
virusoff sounded like a gamemode where you shoot viruses with W, ogarplus had this so that's why I mixed it up

**Comment by Andrews54757** [comment]
Lol.

**Comment by NatsuTheGreat** [comment]
@Andrews54757 Since I am a member so I the right to merge pull requests, close issues and that kind of stuff?

**Pull request closed without merging**
