### PR TITLE
Revert "Dirty fix for #1121"

### PR DESCRIPTION
**Pull request by Andrews54757**
Reverts AJS-development/Ogar-unlimited#1125

### CODE REVIEW

**Comment by NatsuTheGreat** [comment]
Why'd you revert this? :/ This was to prevent the viruses from growing huge when doing virus throw.

**Comment by Agarian** [comment]
It works, but viruses still multiply too much.

**Comment by NatsuTheGreat** [comment]
That is because there is no collision. The ejected mass is in one place and the operation ```feed``` is done very quickly. So they all end up in close. #1132 Should've somewhat fixed them being so close to each other. So try turning collision back on and do virus throw again, just as a test :)

**Comment by Agarian** [comment]
it actually didn't do anything besides change virus shooting speed.

**Comment by Agarian** [comment]
not to be confused with the config

**Comment by NatsuTheGreat** [comment]
What are you talking about? The shooting speed was untouched.

**Pull request merged**
