### PR TITLE
Wrong pr

### PR DESCRIPTION
**Pull request by GhostShot3**
Simple Origin skin fix

Then type this afterwards "I have read and agreed to the contributing guidelines"

### CODE REVIEW

**Comment by GhostShot3** [comment]
oops

**Comment by Agarian** [comment]
Um wut?

**Comment by GhostShot3** [comment]
@Agarian Just created it wrong lol

**Comment by Agarian** [comment]
i made yet another PR

**Comment by GhostShot3** [comment]
@Agarian  Makes a commit to me ?

**Comment by GhostShot3** [comment]
@Agarian have difficulty create pull request : (

**Comment by GhostShot3** [comment]
@Agarian already got

**Comment by LegitSoulja** [comment]
@GhostShot3 I'm telling you to use the github application. It's very simple and easy, but yes you have to learn.

**Comment by GhostShot3** [comment]
@LegitSoulja Yes but I do not understand English only Portuguese

**Pull request closed without merging**
