### PR TITLE
Better Istall dependencies

### PR DESCRIPTION
**Pull request by GhostShot3**
Better design to `Istallation.md`

### CODE REVIEW

**Comment by LegitSoulja** [comment]
Installation needs to be tested for dependencies before merging.

**Comment by GhostShot3** [comment]
@LegitSoulja How to test it ?

**Comment by LegitSoulja** [comment]
Nvm, I was thinking about something else.

**Comment by GhostShot3** [comment]
@LegitSoulja Merge this pull pls ?

**Comment by Agarian** [comment]
cant, it has conflicts

**Comment by GhostShot3** [comment]
@Agarian Why cant merge this ?

**Comment by GhostShot3** [comment]
@Agarian If not the same as merging,close.

**Pull request closed without merging**
