### PR TITLE
Update from ogar

### PR DESCRIPTION
**Pull request by Andrews54757**
Trying to reduce lag and have better physics

### CODE REVIEW

**Comment by Megabyte918** [comment]
@Andrews54757 Why was this closed?

**Comment by Agarian** [comment]
I wanna try this

**Comment by Megabyte918** [comment]
its not finished, just tested and it was full of bugs :( 
I might continue this in my fork tho but adding Ogar physics is gonna take a while

**Comment by LegitSoulja** [comment]
Lol wow

**Comment by Agarian** [comment]
kthen

**Pull request closed without merging**
