### PR TITLE
Chat commands

### PR DESCRIPTION
**Pull request by Andrews54757**
1. Added functions for chat commands
2. Added the color command for chat.
3. Added beforecmsg(player,msg) for plugins

### CODE REVIEW

**Comment by Agarian** [comment]
chat no longer works.

**Comment by Andrews54757** [comment]
@Agarian I was not finished. I know it doesnt work now

**Comment by Agarian** [comment]
Mybad

**Comment by fayizan** [comment]
when this will be merged..? soo waiting to see colour chat command

**Comment by AlexandriteErikParacelsus** [comment]
@fayizan chillax

**Comment by GhostShot3** [comment]
This pull is ready to merge ?

**Pull request merged**
