### PR TITLE
2 skins currently not in ogarul.io/skins

### PR DESCRIPTION
**Pull request by Agarian**
Place your description here.

Then type this afterwards "I have read and agreed to the contributing guidelines"

### CODE REVIEW

**Comment by raphyjb** [comment]
Can we paste in some links to get them on site? I got a link for all new skins!

**Comment by Agarian** [comment]
:O

**Comment by David1ali12** [comment]
cool
lol making some own skin :)
<rat>

**Comment by David1ali12** [comment]
I added!

**Comment by Tokoagar** [comment]
Is the new agar skins added?

**Comment by Agarian** [comment]
idk

**Comment by LegitSoulja** [comment]
@Tokoagar no, we don't have no agar skins.

**Comment by Tokoagar** [comment]
? https://configs-web.agario.miniclippt.com/live/v4/117/FunShine_Bear.png like these one .

Did you stop taking agar skins?

**Comment by LegitSoulja** [comment]
we never took agar skins

**Pull request merged**
