### PR TITLE
Finding typos

### PR DESCRIPTION
**Pull request by GhostShot3**
Founded typos from merge #1318
Then type this afterwards "I have read and agreed to the contributing guidelines"

### CODE REVIEW

**Comment by Agarian** [comment]
they were fine before.

**Comment by NatsuTheGreat** [comment]
And it's Latvia, not lativia ;)

**Comment by David1ali12** [comment]
not confredate its confederate

**Comment by GhostShot3** [comment]
@David1ali12 Thx

**Comment by GhostShot3** [comment]
I think it is now so ready to merge

**Comment by GhostShot3** [comment]
I found another.

**Comment by GhostShot3** [comment]
Now I think he's ready to merge.

**Comment by LegitSoulja** [comment]
Errors?.. Actually typos.

**Comment by GhostShot3** [comment]
@LegitSoulja yes but already packed.

**Comment by LegitSoulja** [comment]
Check over your English, and grammar one more time before merging.

**Comment by GhostShot3** [comment]
@LegitSoulja I know nothing of English i use translator.

**Comment by Agarian** [comment]
We ready to merge?

**Comment by GhostShot3** [comment]
@Agarian Yes.

**Comment by GhostShot3** [comment]
@Agarian Wait a check.

**Comment by Agarian** [comment]
Well apparently "This branch has conflicts that must be resolved"
So cannot merge.

**Comment by GhostShot3** [comment]
@Agarian Which conflicts?

**Comment by Agarian** [comment]
How should i know? I don't know the command line

**Comment by GhostShot3** [comment]
@Agarian  I just changed `botnames` and `customskins` 
It was not to give any error

**Comment by GhostShot3** [comment]
@Agarian If you are not as close, thank you.

**Comment by GhostShot3** [comment]
@Agarian If not solutions, close.

**Comment by Agarian** [comment]
i guess i'll have to close :neutral_face: 
@GhostShot3 You may need to remake the PR

**Comment by GhostShot3** [comment]
@Agarian Okay, I'll do soon.

**Comment by Agarian** [comment]
wait what if i do this for you?

**Comment by GhostShot3** [comment]
@Agarian Do you, it is better.

**Pull request closed without merging**
