### PR TITLE
edits to more commands, i found no bugs.

### PR DESCRIPTION
**Pull request by Agarian**
I have read and agreed to the contributing guidelines

Simply some more minor edits to some commands. Had to update my branch lol, and for some reason, the *"Improvements to merge command"* happened again.

### CODE REVIEW

**Comment by Agarian** [comment]
had to update my branch lol

**Comment by Andrews54757** [comment]
in nojoins.js put the console.log right after the client.norecombine = true code inside the brackets and then put a `break;` right below it

**Comment by Andrews54757** [comment]
or else there is an error if you type a invalid playerid

**Comment by Agarian** [comment]
Ok

**Comment by Agarian** [comment]
why i apparently tend to code more when i'm sick is a mystery to me...

**Pull request merged**
