### PR TITLE
Fixing customskins.txt

### PR DESCRIPTION
**Pull request by GhostShot3**
Fixed skin link and wrong caracter.

Then type this afterwards "I have read and agreed to the contributing guidelines"

### CODE REVIEW

**Comment by LegitSoulja** [comment]
You need to be careful on what you do, and not make many pull requests.

**Comment by GhostShot3** [comment]
@LegitSoulja Ok,I do not know how to put two or more commits in one pullrequest,only i got once,need to learn more

**Comment by LegitSoulja** [comment]
Have you learned how github works yet? You compare branch, with master.

It's easier if you use the github program, to make things ALOT easier.

**Comment by Agarian** [comment]
Accepted

**Comment by GhostShot3** [comment]
@LegitSoulja Thx.

**Pull request merged**
