### PR TITLE
Add back splitMult and line breaks

### PR DESCRIPTION
**Pull request by Agarian**
Place your description here.

Then type this afterwards "I have read and agreed to the contributing guidelines"

### CODE REVIEW

**Comment by Agarian** [comment]
WHY DID THIS CREATE A NEW ONE?

**Comment by Agarian** [comment]
Jeezus ive been frustrated enough today

**Comment by Agarian** [comment]
@Megabyte918 can you test this once it is merged? Im on my mobile and its been a pain trying to add back the configs.

**Comment by firelightning13** [comment]
TypeError: Cannot read property 'splitMult' of undefined
    at Cell.PlayerCell.calcMove (C:\Users\ASUS\Downloads\Ogar-unlimited-master\src\entity\PlayerCell.js:122:33)
    at GameServer.<anonymous> (C:\Users\ASUS\Downloads\Ogar-unlimited-master\src\core\GameServer.js:793:12)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
    at listOnTimeoutNT (timers.js:242:26)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by Megabyte918** [comment]
#1303 was fine lol ima revert this for now

**Pull request merged**
