### PR TITLE
Update PlayerTracker.js

### PR DESCRIPTION
**Pull request by ItzLevvie**

### CODE REVIEW

**Comment by Megabyte918** [comment]
What does this do

**Comment by ItzLevvie** [comment]
@Megabyte918 It fixes the borders(makes it squishy) when it's turned on.

**Comment by Megabyte918** [comment]
Thats cool! Thank you Levvie I cant wait till I get back home to my
computer to try it out :D

**Comment by Agarian** [comment]
Nice!

**Pull request merged**
