### PR TITLE
Requested free-roam update integration

### PR DESCRIPTION
**Pull request by Luka967**
Actually it was just copy and paste as `PlayerTracker.js` wasn't edited at all

### CODE REVIEW

**Comment by Andrews54757** [comment]
BUG
```
[Game] By The AJS development team
[Game] Loaded stats server on port 88
[Game] Listening on port 443
[Game] Current game mode is Free For All
[Autopause] The Game Was Paused to save memory. Join the game to resume!
>[Autopause] Game Resumed!
addbot 20
[Console] Added 20 player bots
>TypeError: Cannot read property 'length' of undefined
    at PlayerTracker.update (C:\Users\Min\Desktop\Ogar-unlimited-master\src\Play
erTracker.js:148:43)
    at GameServer.updateClients (C:\Users\Min\Desktop\Ogar-unlimited-master\src\
GameServer.js:533:39)
    at GameServer.mainLoop (C:\Users\Min\Desktop\Ogar-unlimited-master\src\GameS
erver.js:482:14)
    at wrapper [as _onTimeout] (timers.js:276:11)
    at Timer.listOnTimeout (timers.js:93:15)

```

**Comment by Luka967** [comment]
I'm too tired to do it now. Sorry.

**Comment by Andrews54757** [comment]
I fixed it anyway

**Comment by Andrews54757** [comment]
for now

**Comment by NatsuTheGreat** [comment]
@Andrews54757 Did you premanently fix it

**Pull request merged**
