### PR TITLE
LARGE FORMATTING FIX

### PR DESCRIPTION
**Pull request by NatsuTheGreat**
## This did get tiring so I left out some files. If you see something wrong, tell me. I may fromat the other missed files but I think they're okay. This is about 80% of all the files formatted.

### CODE REVIEW

**Comment by NatsuTheGreat** [comment]
I don't know what HoundCI just did lol...

**Comment by Megabyte918** [comment]
@NatsuTheGreat **HOLY SHITE** how long did this take you?

**Comment by NatsuTheGreat** [comment]
@Megabyte918 I have a headache :(

**Comment by Megabyte918** [comment]
you really want to be a dev dont you lol this is a pretty big contribution

**Comment by NatsuTheGreat** [comment]
@Megabyte918 I really had nothing to do anyways xD

**Comment by Megabyte918** [comment]
my crappy laptop cant even load the files changed cause its so much lmao the webpage crashes

**Comment by NatsuTheGreat** [comment]
@Megabyte918 Mine was able to handle it, sorry lol xD

**Comment by Megabyte918** [comment]
trade computers?

**Comment by NatsuTheGreat** [comment]
Come to my house, only 400$ :$

**Comment by Megabyte918** [comment]
lmao

**Comment by Megabyte918** [comment]
@Andrews54757 you have to see this its crazy

**Comment by NatsuTheGreat** [comment]
What if he's sleeping and wakes up to something like this xD

**Comment by Megabyte918** [comment]
lol lets hope he doesnt get a headache too

**Comment by NatsuTheGreat** [comment]
xD

**Comment by Megabyte918** [comment]
hey m8 while your at it can you change `splitspeed` in gameserver.ini to 100 its more similar to vanilla agario

**Comment by MichaelLeeHobbs** [comment]
@NatsuTheGreat We have a .editorconfig which handles formatting for us. I use WebStorm and regularly run format code on the whole project. Secondly, most IDE's now support .editorconfig so you do not have to do this by hand.

**Comment by MichaelLeeHobbs** [comment]
@NatsuTheGreat I'm going to merge this so I can run the code formatter.

**Comment by NatsuTheGreat** [comment]
@Megabyte918 Sorry, I had to go to sleep.

**Comment by Agarian** [comment]
# LOL CALM THE BOLD ANDREWS :smile:

**Pull request merged**
