### PR TITLE
Quite a few command improvements

### PR DESCRIPTION
**Pull request by Agarian**
- Playerlist is neater, and displays a message if no players/bots are in the server.
- Gamemode command has an addon: `gamemode list`. Lists all gamemodes.
- Merge command is now like ogar's.
- Addbot command doesn't add bots at EXACTLY the same time, reduces lag when adding bots.
- Garbage collection doesn't change the leaderboard anymore.
- The name command can now account for unnamed cells.

I have read and agreed to the contributing guidelines

### CODE REVIEW

**Comment by NatsuTheGreat** [comment]
Lets be honest, this is pretty much all from ogar :/

**Comment by Agarian** [comment]
Only `playerlist` and `merge` is :P

**Comment by NatsuTheGreat** [comment]
bot adding, added by luka. :D

**Comment by Agarian** [comment]
Well yes

**Pull request merged**
