### PR TITLE
Update Physics.js

### PR DESCRIPTION
**Pull request by NatsuTheGreat**
Place your description here.

Then type this afterwards "I have read and agreed to the contributing guidelines"

Credits to Agarian.

### CODE REVIEW

**Comment by Agarian** [comment]
Lol you used my code

**Comment by Agarian** [comment]
I was thinking of making a split speed version config

**Comment by NatsuTheGreat** [comment]
Hey buddy, did you read this part????:

> Credits to Agarian.

**Comment by NatsuTheGreat** [comment]
If anything, you're the one who used my dynamic split code.

**Comment by Agarian** [comment]
? I got that from David1ali12

**Comment by Agarian** [comment]
The 20000 mass condition i added

**Comment by NatsuTheGreat** [comment]
Don't even lie now, it originated from me. I know you've been on MegaByte's workspace, he had my code. You just took it.

**Comment by NatsuTheGreat** [comment]
The dynamic splitspeed, the three lines I removed... Those are not yours. You copied them.

**Comment by NatsuTheGreat** [comment]
What do you have to say for yourself?

**Comment by David1ali12** [comment]
Wtf I made this shit credits to Agarian I'm so  :angry:

**Comment by David1ali12** [comment]
You both lie its originated from me

**Comment by NatsuTheGreat** [comment]
I did not know, sorry, David. I will update it.

**Comment by NatsuTheGreat** [comment]
Same with me here, I gave megabyte my code, and agarain took it too.

**Comment by David1ali12** [comment]
@NatsuTheGreat btw  can you help me with ogarul + I need your help its almost done
It does not replace main_out.js https://ide.c9.io/david2ali19/ogarplus-ext

**Comment by Agarian** [comment]
Youre making a big deal over something i never said was mine in the first place.

**Comment by NatsuTheGreat** [comment]
You never credited either.

**Pull request merged**
