### PR TITLE
MotherCells are in their own file

### PR DESCRIPTION
**Pull request by NatsuTheGreat**
My last pull request had a small correction that needed to be done, fix it here. If you get error, please let me know.

### CODE REVIEW

**Comment by Andrews54757** [comment]
I had an error when testing so I kept the mothercell file but reversed expiramental

**Comment by NatsuTheGreat** [comment]
@Andrews54757 Mind giving me the error so I can look into it?

**Comment by Andrews54757** [comment]
it was `refrence error, MotherCell is not defined at Mode.Experimental.spawnMotherCell`

**Comment by NatsuTheGreat** [comment]
@Andrews54757 Can I have the full error code that it says in your console?

**Comment by Andrews54757** [comment]
i cant, it wont let me copy and paste

**Comment by Andrews54757** [comment]
but the issue is in experimental.js

**Comment by NatsuTheGreat** [comment]
Do this then:

Right click,
click "Mark"
Select all of the error code
and hit enter or return

And then send it to me

**Comment by Andrews54757** [comment]
>colortext bold
Text is now Bold
>[Autopause] Game Resumed!
ReferenceError: MotherCell is not defined
    at Mode.Experimental.spawnMotherCell (C:\Users\Min\Desktop\Ogar-unlimited-ma
ster\src\gamemodes\Experimental.js:81:21)
    at Mode.Experimental.onTick (C:\Users\Min\Desktop\Ogar-unlimited-master\src\
gamemodes\Experimental.js:121:14)
    at GameServer.gamemodeTick (C:\Users\Min\Desktop\Ogar-unlimited-master\src\G
ameServer.js:459:19)
    at GameServer.mainLoop (C:\Users\Min\Desktop\Ogar-unlimited-master\src\GameS
erver.js:478:29)
    at wrapper [as _onTimeout] (timers.js:276:11)
    at Timer.listOnTimeout (timers.js:93:15)

**Comment by Andrews54757** [comment]
if you dont see an error, either disable autopause or play the game

**Comment by Andrews54757** [comment]
also if you use the newest version of ogar unlimited, Remember, you wont see an error because I reverted it

**Comment by NatsuTheGreat** [comment]
Ahh I see what I did wrong

Go to the Experimental.js file, hit enter after line 5 and add this: 

````
var MotherCell = require('../entity/MotherCell');
````

**Comment by Andrews54757** [comment]
I tried that and another error pops up (I tried it 8 minutes ago)

**Comment by NatsuTheGreat** [comment]
Alrighty, give me the error

**Comment by Andrews54757** [comment]
| (_)     (_)_           | |
  ___   ____  ____  ____    _   _ ____ | |_ ____  _| |_  ____ _ | |
 / _ \ / _  |/ _  |/ ___)  | | | |  _ \| | |    \| |  _)/ _  ) || |
| |_| ( ( | ( ( | | |      | |_| | | | | | | | | | | |_( (/ ( (_| |
 \___/ \_|| |\_||_|_|       \____|_| |_|_|_|_|_|_|_|\___)____)____|
      (_____|
[Game] Ogar Unlimited - An open source Agar.io server implementation
[Game] By The AJS development team
[Game] Loaded stats server on port 88
[Game] Listening on port 443
[Game] Current game mode is Experimental
>addbot 10
[Console] Added 10 player bots
>TypeError: MotherCell is not a function
    at Mode.Experimental.spawnMotherCell (C:\Users\Min\Desktop\Ogar-unlimited-ma
ster\src\gamemodes\Experimental.js:82:17)
    at Mode.Experimental.onTick (C:\Users\Min\Desktop\Ogar-unlimited-master\src\
gamemodes\Experimental.js:122:14)
    at GameServer.gamemodeTick (C:\Users\Min\Desktop\Ogar-unlimited-master\src\G
ameServer.js:459:19)
    at GameServer.mainLoop (C:\Users\Min\Desktop\Ogar-unlimited-master\src\GameS
erver.js:478:29)
    at wrapper [as _onTimeout] (timers.js:276:11)
    at Timer.listOnTimeout (timers.js:93:15)

**Comment by NatsuTheGreat** [comment]
Can you send me your exp file?

**Comment by Andrews54757** [comment]
sure
```
var FFA = require('./FFA'); // Base gamemode
var Cell = require('../entity/Cell');
var Food = require('../entity/Food');
var Virus = require('../entity/Virus');
var VirusFeed = require('../entity/Virus').prototype.feed;
var MotherCell = require('../entity/MotherCell');

function Experimental() {
    FFA.apply(this, Array.prototype.slice.call(arguments));

    this.ID = 2;
    this.name = "Experimental";
    this.specByLeaderboard = true;

    // Gamemode Specific Variables
    this.nodesMother = [];
    this.tickMother = 0;
    this.tickMotherS = 0;

    // Config
    this.motherCellMass = 200;
    this.motherUpdateInterval = 5; // How many ticks it takes to update the mother cell (1 tick = 50 ms)
    this.motherSpawnInterval = 100; // How many ticks it takes to spawn another mother cell - Currently 5 seconds
    this.motherMinAmount = 5;
}

module.exports = Experimental;
Experimental.prototype = new FFA();

// Gamemode Specific Functions

Experimental.prototype.updateMotherCells = function(gameServer) {
    for (var i in this.nodesMother) {
        var mother = this.nodesMother[i];

        // Checks
        mother.update(gameServer);
        mother.checkEat(gameServer);
    }
}

Experimental.prototype.spawnMotherCell = function(gameServer) {
    // Checks if there are enough mother cells on the map
    if (this.nodesMother.length < this.motherMinAmount) {
        // Spawns a mother cell
        var pos = gameServer.getRandomPosition();

        // Check for players
        for (var i = 0; i < gameServer.nodesPlayer.length; i++) {
            var check = gameServer.nodesPlayer[i];

            var r = check.getSize(); // Radius of checking player cell

            // Collision box
            var topY = check.position.y - r;
            var bottomY = check.position.y + r;
            var leftX = check.position.x - r;
            var rightX = check.position.x + r;

            // Check for collisions
            if (pos.y > bottomY) {
                continue;
            }

            if (pos.y < topY) {
                continue;
            }

            if (pos.x > rightX) {
                continue;
            }

            if (pos.x < leftX) {
                continue;
            }

            // Collided
            return;
        }

        // Spawn if no cells are colliding
        var m = new MotherCell(gameServer.getNextNodeId(), null, pos, this.motherCellMass);
        gameServer.addNode(m);
    }
};

// Override

Experimental.prototype.onServerInit = function(gameServer) {
    // Called when the server starts
    gameServer.run = true;

    // Special virus mechanics
    Virus.prototype.feed = function(feeder, gameServer) {
        gameServer.removeNode(feeder);
        // Pushes the virus
        this.setAngle(feeder.getAngle()); // Set direction if the virus explodes
        this.moveEngineTicks = 5; // Amount of times to loop the movement function
        this.moveEngineSpeed = 30;

        var index = gameServer.movingNodes.indexOf(this);
        if (index == -1) {
            gameServer.movingNodes.push(this);
        }
    };

    // Override this
    gameServer.getRandomSpawn = gameServer.getRandomPosition;
};

Experimental.prototype.onTick = function(gameServer) {
    // Mother Cell updates
    if (this.tickMother >= this.motherUpdateInterval) {
        this.updateMotherCells(gameServer);
        this.tickMother = 0;
    } else {
        this.tickMother++;
    }

    // Mother Cell Spawning
    if (this.tickMotherS >= this.motherSpawnInterval) {
        this.spawnMotherCell(gameServer);
        this.tickMotherS = 0;
    } else {
        this.tickMotherS++;
    }
};

Experimental.prototype.onChange = function(gameServer) {
    // Remove all mother cells
    for (var i in this.nodesMother) {
        gameServer.removeNode(this.nodesMother[i]);
    }
    // Add back default functions
    Virus.prototype.feed = VirusFeed;
    gameServer.getRandomSpawn = require('../GameServer').prototype.getRandomSpawn;
};
```

**Comment by NatsuTheGreat** [comment]
Try this:

````
var FFA = require('./FFA'); // Base gamemode
var Cell = require('../entity/Cell');
var Food = require('../entity/Food');
var Virus = require('../entity/Virus');
var VirusFeed = require('../entity/Virus').prototype.feed;
var MotherCell = require('../entity/MotherCell');

function Experimental() {
    FFA.apply(this, Array.prototype.slice.call(arguments));

    this.ID = 2;
    this.name = "Experimental";
    this.specByLeaderboard = true;
    
    // Gamemode Specific Variables
    this.nodesMother = [];
    this.tickMother = 0; 
    this.tickMotherS = 0;
    
    // Config
    this.motherCellMass = 200;
    this.motherUpdateInterval = 5; // How many ticks it takes to update the mother cell (1 tick = 50 ms)
    this.motherSpawnInterval = 100; // How many ticks it takes to spawn another mother cell - Currently 5 seconds
    this.motherMinAmount = 5;
}

module.exports = Experimental;
Experimental.prototype = new FFA();

// Gamemode Specific Functions

Experimental.prototype.updateMotherCells = function(gameServer) {
    for (var i in this.nodesMother) {
        var mother = this.nodesMother[i];
        
        // Checks
        mother.update(gameServer);
        mother.checkEat(gameServer);
    }
};

Experimental.prototype.spawnMotherCell = function(gameServer) {
	// Checks if there are enough mother cells on the map
    if (this.nodesMother.length < this.motherMinAmount) {
        // Spawns a mother cell
        var pos =  gameServer.getRandomPosition();

        // Check for players
        for (var i = 0; i < gameServer.nodesPlayer.length; i++) {
            var check = gameServer.nodesPlayer[i];

            var r = check.getSize(); // Radius of checking player cell

            // Collision box
            var topY = check.position.y - r;
            var bottomY = check.position.y + r;
            var leftX = check.position.x - r;
            var rightX = check.position.x + r;

            // Check for collisions
            if (pos.y > bottomY) {
                continue;
            }

            if (pos.y < topY) {
                continue;
            }

            if (pos.x > rightX) {
                continue;
            }

            if (pos.x < leftX) {
                continue;
            }

            // Collided
            return;
        }

        // Spawn if no cells are colliding
        var m = new MotherCell(gameServer.getNextNodeId(), null, pos, this.motherCellMass);
        gameServer.addNode(m); 
    }
};

// Override

Experimental.prototype.onServerInit = function(gameServer) {
    // Called when the server starts
    gameServer.run = true;

    // Override this
    gameServer.getRandomSpawn = gameServer.getRandomPosition;
};

Experimental.prototype.onTick = function(gameServer) {
    // Mother Cell updates
    if (this.tickMother >= this.motherUpdateInterval) {
    	this.updateMotherCells(gameServer);
    	this.tickMother = 0;
    } else {
    	this.tickMother++;
    }
    
    // Mother Cell Spawning
    if (this.tickMotherS >= this.motherSpawnInterval) {
    	this.spawnMotherCell(gameServer);
    	this.tickMotherS = 0;
    } else {
    	this.tickMotherS++;
    }
};

Experimental.prototype.onChange = function(gameServer) {
    // Remove all mother cells
    for (var i in this.nodesMother) {
        gameServer.removeNode(this.nodesMother[i]);
    }
    // Add back default functions
    gameServer.getRandomSpawn = require('../GameServer').prototype.getRandomSpawn;
};
````

**Comment by Andrews54757** [comment]
Again

```
[Game] Loaded stats server on port 88
[Game] Listening on port 443
[Game] Current game mode is Experimental
>addbot 10
[Console] Added 10 player bots
>TypeError: MotherCell is not a function
    at Mode.Experimental.spawnMotherCell (C:\Users\Min\Desktop\Ogar-unlimited-ma
ster\src\gamemodes\Experimental.js:82:17)
    at Mode.Experimental.onTick (C:\Users\Min\Desktop\Ogar-unlimited-master\src\
gamemodes\Experimental.js:108:14)
    at GameServer.gamemodeTick (C:\Users\Min\Desktop\Ogar-unlimited-master\src\G
ameServer.js:459:19)
    at GameServer.mainLoop (C:\Users\Min\Desktop\Ogar-unlimited-master\src\GameS
erver.js:478:29)
    at wrapper [as _onTimeout] (timers.js:276:11)
    at Timer.listOnTimeout (timers.js:93:15)

```

**Comment by NatsuTheGreat** [comment]
:(

**Comment by Andrews54757** [comment]
:+1:

**Comment by NatsuTheGreat** [comment]
before 
````
MotherCell.prototype = new Cell(); // Base
````
type in
````
module.exports = MotherCell;
````

**Pull request closed without merging**
