### PR TITLE
The Stability Update

### PR DESCRIPTION
**Pull request by Andrews54757**
TODO:

*  ~~Get rid of unnecessary things that slow the server (gameServer._nodes is one)~~ 
* ~~Fix most bugs and test out most features and gamemodes (will take a while)~~
* ~~Simplify code~~
* ~~Catch errors so it doesnt stop the game~~
* ~~add features~~

**READY FOR MERGE, SCHEDULED TOMORROW**

RESULTS:
* Faster server, reduced lag
* Less bugs
* Socket protection
* Skins.
* Advanced Multiverse

PROGRESS:
* Got rid of gameServer._nodes & other ._nodes variables
* 700 bots = 0 lag (BTW, My computer came with a windows vista originally)
* Done with phase 1
* Spawn command fixed
* experimental 2 fixed
* TeamZ fixed
* nocollisionteamz fixed
* specChatAllowed option
* adminconfig fixed
* beforechat(player) plugin support
* plugin add is protected as security feature
* Reset command more effecient
* Fixed & recoded Rainbow
* Recoded unlimitffa
* Recoded Virus Off
* Skins. (https://cloud.githubusercontent.com/assets/13282284/15720560/ec62ded8-2802-11e6-9bec-4d967d5f71d5.png)
* Multiverse Servers are listed in the client (https://cloud.githubusercontent.com/assets/13282284/15720589/0c68bc20-2803-11e6-9f0a-5b4dca8c8689.png)
* Multiverse create has a new argument `title` at end (multiverse create [name] [port] [gamemode] [title]). (title is what is displayed at the client. Optional)
* Packets wont crash the server as easily
* Fixed multiple bugs.

### CODE REVIEW

**Comment by NatsuTheGreat** [comment]
What gamemodes? :P

**Comment by problemsofworld** [comment]
moving unnecessary things in gameserver and make them as plugins
it gonna help to reduce lag am not sure

**Comment by XenoYT** [comment]
+ Skins

**Comment by Agarian** [comment]
this is exactly what we needed!!!

**Comment by Megabyte918** [comment]
Holy cranberries can't wait

**Comment by GhostShot3** [comment]
"700 bots = 0 lag" really lol !!!

**Comment by raphyjb** [comment]
how can i get the update?? Please explain (:

**Comment by raphyjb** [comment]
Is there a way for u guys to add zoom out ? Alot of peeps are complaining about this in my Small server

**Comment by Agarian** [comment]
i tested it, why do viruses randomly despawn? that ain't right

**Comment by loganagar32** [comment]
@Andrews54757  me dev pleaseeeeeeeeeeeeeeee

**Comment by raphyjb** [comment]
Andrews54757, is there a way to know how to change all of this updates in the new one? I dont get it.. so many things to change im presently doing it by hand.. its lonnnnnggg

**Comment by Andrews54757** [comment]
?

**Comment by raphyjb** [comment]
just did update all... nvm

**Comment by Agarian** [comment]
https://github.com/AJS-development/Ogar-unlimited/tree/stable

**Comment by Megabyte918** [comment]
@Andrews54757 can you make a config that allows bots to team or not? for the people who dont want them to

**Comment by PrinceDark9243** [comment]
make its like this `mass [ID] [SUB-CMD] [AMOUNT]` ex;`mass 1 add 2000`
Sub Command list:`add,remove,set`

**Comment by Influxx** [comment]
Bug: when a virus gets shot by 2 or more cell pieces, the virus shot speed changes and some of the viruses get "teleported" to their new position.

Performance: Implement the [uws module](https://www.npmjs.com/package/uws) for faster socket speed and lower memory usage.

Performance: Make use of [Node.js clustering](https://nodejs.org/api/cluster.html) for multi-core capabilities so that network IO isn't performed on the same thread that performs world/entity ticking (and allow for multithreaded ticking).


I would personally like to see a stable, high-performing OgarUL rather than an OgarUL with dozens of new features and gamemodes.

**Comment by Agarian** [comment]
um so is the rainbow gamemode fixable?

**Comment by LegitSoulja** [comment]
@Agarian lol I dont think it's broken, it could be the client. I haven't looked into the game modes but I'm interested in making one.

**Comment by Andrews54757** [comment]
@Agarian yep. il fix soon

**Comment by Agarian** [comment]
I tried changing a few things in the file but got the same error lol

**Comment by Agarian** [comment]
I think the UWS idea that @influxx gave may do well

**Comment by LegitSoulja** [comment]
Please go through the code when your done and as much plugin API essentials, returns, and callbacks. Thanks :)

**Comment by Agarian** [comment]
i still think this break was a mistake. (no rhyme intended)

**Comment by Agarian** [comment]
But seriously, do you know what a cell's border looks like? Its the part that's usually darker that the rest of the cell. How can i make this cell border appear even in smooth render? 
(smooth render is when you hit a certain size, all entities render more "simply" and makes the game lag less. I still want this to happen but i aso want a cell's border to remain)

**Comment by Agarian** [comment]
FFS its starting to get obvious no one gives a crap. How rude.

**Comment by Andrews54757** [comment]
@Agarian Spectate works. You have to click the settings button to get it

**Comment by Andrews54757** [comment]
Dont be an internet addict

**Comment by Agarian** [comment]
can you at least tell me why this new text art i was gonna test is not appearing in the console properly?

    writeTitle() {
    // Start msg
    this.log("\u001B[33m");
    this.log("  ____   _____          _____    _    _ _   _ _      _____ __  __ _____ _______ ______ _____  ");
    this.log(" / __ \ / ____|   /\   |  __ \  | |  | | \ | | |    |_   _|  \/  |_   _|__   __|  ____|  __ \ ");
    this.log("| |  | | |  __   /  \  | |__) | | |  | |  \| | |      | | | \  / | | |    | |  | |__  | |  | |");
    this.log("| |  | | | |_ | / /\ \ |  _  /  | |  | | . ` | |      | | | |\/| | | |    | |  |  __| | |  | |");
    this.log("| |__| | |__| |/ ____ \| | \ \  | |__| | |\  | |____ _| |_| |  | |_| |_   | |  | |____| |__| |");
	this.log(" \____/ \_____/_/    \_\_|  \_\  \____/|_| \_|______|_____|_|  |_|_____|  |_|  |______|_____/ ");
    this.log("\u001B[0m");

    this.log("\x1b[32m[Game] Ogar Unlimited - An open source Agar.io server implementation");
    this.log("[Game] By The AJS development team\x1b[0m");
    this.log("[Game] Server version is " + this.version);
  }

**Comment by Agarian** [comment]
it seems to be ignoring backslashes when displayed in the console

**Comment by Andrews54757** [comment]
you need to escape it

**Comment by Agarian** [comment]
like unescape?

**Comment by Andrews54757** [comment]
instead of \\, you have to use \\\

**Comment by Agarian** [comment]
oh

**Comment by Agarian** [comment]
OK i did that, this is the console's result:

      ____   _____          _____    _    _ _   _ _      _____ __  __ _____ _______ ______ _____  
 / __ \ / ____|   /\   |  __ \  | |  | | \ | | |    |_   _|  \/  |_   _|__   __|  ____|  __ \ 
| |  | | |  __   /  \  | |__) | | |  | |  \| | |      | | | \  / | | |    | |  | |__  | |  | |
| |  | | | |_ | / /\ \ |  _  /  | |  | | . ` | |      | | | |\/\| | | |    | |  |  __| | |  | |
| |__| | |__| |/  ¯¯  \| |    | |__| | |\  | |____ _| |_| |  | |_| |_   | |  | |____| |__| |
 \____/ \_____/_/¯¯¯¯\_\_|  \_\  \____/|_| \_|______|_____|_|  |_|_____|  |_|  |______|_____/

**Comment by Agarian** [comment]
Done, but this is the consoles result:

capture

**Comment by Andrews54757** [comment]
It doesnt matter, Im gonna change the interface completely anyway

**Comment by Agarian** [comment]
One more suggestion: a `randomMinionUpdate` config, it would do the same action as the `randomBotSmartness` config does, but instead it only affects minions.

**Comment by Megabyte918** [comment]
anybody online? i need help with something

**Pull request merged**
