### PR TITLE
Update PlayerCell.js

### PR DESCRIPTION
**Pull request by Megabyte918**
Fixed smaller cells pushing against bigger cells (bigger cells now push harder against smaller ones)
Fixed collision causing bigger cells to teleport when splitting through smaller ones

### CODE REVIEW

**Comment by Agarian** [comment]
**BUG:**
capture

**Comment by Megabyte918** [comment]
try replacing the `PlayerCell.prototype.simplecollide` function with this one: 
<code>
PlayerCell.prototype.simpleCollide = function(x1,y1,check,d) {
    // Simple collision check
    var len = d >> 0; // Width of cell + width of the box (Int)

    return (this.abs(x1 - check.position.x) < len) &&
           (this.abs(y1 - check.position.y) < len);
};
</code>

**Comment by Megabyte918** [comment]
try replacing `PlayerCell.prototype.simpleCollide` with this one
`PlayerCell.prototype.simpleCollide = function(x1,y1,check,d) {
    // Simple collision check
    var len = d >> 0; // Width of cell + width of the box (Int)

    return (this.abs(x1 - check.position.x) < len) &&
           (this.abs(y1 - check.position.y) < len);
};`

**Comment by Agarian** [comment]
Can you actually add this(and have it working)? This would've been a great idea!

**Pull request closed without merging**
