### PR TITLE
Big Update

### PR DESCRIPTION
**Pull request by Andrews54757**
New things

(Done) Minions are separate and has more parameters
(Done) Update command is improved
(Done) Minions avoiding others can be confined
(Done) ban file
(Done) opbyip files
(Done) more default custom skins
(Done) proportional option (but may cause visual problems)
(Done) other things

### CODE REVIEW

**Comment by Andrews54757** [comment]
i will merge when the test passes

**Comment by Agarian** [comment]
there has to be another way to control these things without having to press q then use w and spacebar
its very annoying

**Comment by ErikParacelsus** [comment]
Agarian is right. Instead of press q to control them, why don't you just make the minion eject when press "R" and split when press "E".

**Comment by Agarian** [comment]
he says the client only sends W, Q, and spacebar

**Comment by ErikParacelsus** [comment]
Yes, i already know.

**Comment by Agarian** [comment]
then why ask that question?

**Comment by Agarian** [comment]
@Andrews54757 Passed

**Comment by Andrews54757** [comment]
wait, i am going to add more features and i am going to update in a batch

**Comment by Agarian** [comment]
like i said b4, is there a way to control the minions with the keys E and R?

**Comment by Andrews54757** [comment]
No

**Comment by Andrews54757** [comment]
No

**Comment by Andrews54757** [comment]
No

**Comment by Andrews54757** [comment]
No

**Comment by Andrews54757** [comment]
No

**Comment by Agarian** [comment]
well, at this point i have lost all interest in these minions.

**Comment by Agarian** [comment]
just incase u ddnt know, the minions and playerbots do not absorb mass correctly.

**Pull request merged**
