### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by firelightning13**
Changed from `continue` to `return`

I have read and agreed to the contributing guidelines

### CODE REVIEW

**Comment by Megabyte918** [comment]
doesnt this make you unable to w?

**Comment by Agarian** [comment]
When return was changed to continue in this case, it caused another w bug.

**Comment by Agarian** [comment]
@Megabyte918 one of ur pulls caused an error:

/home/ubuntu/workspace/src/core/GameServer.js:1131
continue;
^^^^^^^^

SyntaxError: Illegal continue statement
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/home/ubuntu/workspace/src/core/ControlServer.js:6:20)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)

happens on lines 1131, 1135, and 1139 in gameserver.js

**Comment by firelightning13** [comment]
@Megabyte918 You cant change all of it, some of them needs to `return`, some of them needs `continue`

**Comment by Megabyte918** [comment]
kill me

**Comment by Megabyte918** [comment]
AGHHH I MESS EVERYTHING UP

**Comment by firelightning13** [comment]
At least W is working, so calm down

**Comment by MichaelLeeHobbs** [comment]
@Megabyte918 eventually all the continues will go away. If you see a forEach this it will need a return where a a for (var i = 0; i < someThing; i++ ) { ... it will need a continue.

**Comment by firelightning13** [comment]
Oooh, ok noted :D

**Pull request merged**
