### PR TITLE
Building a better anti bot system...

### PR DESCRIPTION
**Pull request by Andrews54757**
In this update,  i added a feature that if multiple people's mouses are the same, it kicks them off.

### CODE REVIEW

**Comment by hassanila97** [comment]
Nice

**Comment by Andrews54757** [comment]
thanks

**Comment by NatsuTheGreat** [comment]
Does it really work? And what if someone is multiboxing?

**Comment by Andrews54757** [comment]
It works, try it, use davidmanns bots on Ogar unlimited, disabling scramble and verify

**Comment by Andrews54757** [comment]
also, remember that this features mech is sort of a secret and it is in the list of do not copy

**Comment by NatsuTheGreat** [comment]
Well what is the bots are set to "Follow my cell"?

**Comment by Andrews54757** [comment]
its the same

**Pull request merged**
