### PR TITLE
Requested merge revamp

### PR DESCRIPTION
**Pull request by Luka967**
However `cellUpdateTick` (forwarding `updateCells`) must be triggered every 50 ms instead of 1 second to make sure it's precise.

_it's 16:16 and i'm already tired :(_

### CODE REVIEW

**Comment by Andrews54757** [comment]
Thanks

**Comment by Andrews54757** [comment]
Wait, how do you fix alll my commands and stuff like Merge or nojoin? they dont work anymore. (im sorry your tired)

**Comment by ItzLevvie** [comment]
.

**Comment by Luka967** [comment]
Oh ok, i'll do it. i just came back, was afk.

**Comment by Luka967** [comment]
btw, I'm going to add the merge command in Ogar, however I don't have an ETA for now.

**Pull request merged**
