### PR TITLE
Child Processes - Reducing Lag

### PR DESCRIPTION
**Pull request by Andrews54757**
"NodeJS is single threaded" is probably one of the most famous lines by nodejs programmers. But, actually, it is not 100% single threaded. There is something called ChildProccesses. I, have just learned how to use them (hours of looking at the docs and experimentation) . This allows servers using multiple cores to shine.

Note that bots/minions don't apply

## Advantages
* Less lag (no more jerky movements,smooth );
* Multi-core support

## Disadvantages
* You cannot run out of the src folder

# TODO

- [x] Make GetCellsInRange run in a child.
- [ ] Make CalcViewBox run in a child.
- [x] Make virus feed run in a child
- [x]  Make updatenodes run in a child
- [x]  View box update now depends on client lag.
- [x]  Fix chat commands
- [x] Add more plugin functions
- [x] Add a maxChild Config

### CODE REVIEW

**Comment by Megabyte918** [comment]
Sweet I can't w8

**Comment by Megabyte918** [comment]
Will doing this hopefully fix the spectate bug?

**Comment by LegitSoulja** [comment]
You mean these are clusters right?

**Comment by Agarian** [comment]
i wanna test this even though its not finished

**Comment by Andrews54757** [comment]
Yep. I am still thinking of something @LegitSoulja . Should every player have his own child process? If so, it will increase lag the more the players because new processes use lots of resources, but I wonder if the child will crash if there is only one for the entire server. I don't really know. Do you?

**Comment by LegitSoulja** [comment]
@Andrews54757 that could cause alot of stress, also with bots and minions it will be created aswell. There can be over thousands of players, and thousands of processes if not closed afterwards.

Maybe 10-20 players per process? Or either just all the physics and main things that causes lag should be in another process.

**Comment by XtremePlayzCODE** [comment]
WOO! Hopefully I won't have to buy 8gb of ram to reduce lag for my ogarul servers lol

**Comment by DarkZYT** [comment]
Yeah

**Comment by GhostShot3** [comment]
@Andrews54757 
Because you never change your picture?

**Comment by XtremePlayzCODE** [comment]
DO NOT USE THIS AND DO MINION 1 100
I REPEAT
DO
NOT
DO 
MINION 1 100!

**Comment by Agarian** [comment]
yeah imma keep my version of ogarUL as to not break it more than it already is.

**Comment by XtremePlayzCODE** [comment]
good idea lol

**Comment by Andrews54757** [comment]
@XtremePlayzCODE I developed a way to fix the minion and bots bug. (i just discovered) but this is still not finished

**Comment by XtremePlayzCODE** [comment]
http://imgur.com/G7nv1Pl <-- another error
good luck with this project

**Comment by genckaptan55** [comment]
I tried to use jxcore with ogar UL but it didnt work. Is it possbile to make it work with jxcore?

**Comment by LegitSoulja** [comment]
@XtremePlayzCODE Stop annoying people. And what's the good luck for? Don't never doubt anyone. Sounds to like to me you want a kick in the nuts

**Comment by Agarian** [comment]
So i was finally able to do that `Speczoom depending on cell splitting` feature. i'll make a PR on that when this is merged as to not cause conflicts.

**Comment by Megabyte918** [comment]
@Agarian I don't think what you edited affects this pr, you can make your changes safely

**Comment by Agarian** [comment]
This'll be interesting.

**Comment by XtremePlayzCODE** [comment]
@LegitSoulja I was actually saying good luck to Andrews, not being sarcastic. My main purpose here is to help AJS with finding bugs, that was what I did before I got banned and that's my main goal here, not to annoy.

And ps, why do I need a kick in the nuts another time after you said my ip address to the ogarul nolag server?

**Comment by fayizan** [comment]
wow one more to go..!!

**Comment by LegitSoulja** [comment]
I'm having a feeling this going to take away the fun for having multiple servers at once. Is it possible to add a CPU limit of how many cores you can use? I have 24 cores, and able to make atleast 48 threads. My ram is higher than a bird. Looks like if I ever want to host servers again my CPU needs upgrading. Although my CPU is overclocked. Looks like it's (Time for a new motherboard :/).

**Comment by Agarian** [comment]
lol i am not updating to this

**Comment by Agarian** [comment]
@fayizan one more?

**Comment by XtremePlayzCODE** [comment]
did u delete my comment?

**Comment by firelightning13** [comment]
@Agarian 
> | | Make CalcViewBox run in a child

**Comment by Agarian** [comment]
@XtremePlayzCODE who? me?

**Comment by XtremePlayzCODE** [comment]
LegitSoulja deleted my comment. Anyways he told everyone in an OgarUL server my ip

**Comment by GetRektAgario** [comment]
What is the estimated time of finish for this project?

**Comment by LegitSoulja** [comment]
what is CalcViewBox? Maybe I can finish it.

**Comment by Megabyte918** [comment]
@LegitSoulja its a function in playertracker.js used for calculating the size of and whats inside a players view range during spectate/freeroam

**Comment by LegitSoulja** [comment]
Should we change that? Because I heard calculating by points and not size is less lag

**Comment by Megabyte918** [comment]
Lets wait until Andrew comes back, he might be working on it as we speak who knows :P

**Comment by LegitSoulja** [comment]
It doesn't even matter no more. I may or not not be back for a while

**Comment by Agarian** [comment]
Why?

**Comment by LegitSoulja** [comment]
Work, and other things. I won't have time no more to do things like I used to so :/.

**Comment by mrzack506** [comment]
@LegitSoulja Calculating by size does reduce lag, but the downside is that it will be harder for players to configure their server.

**Comment by Agarian** [comment]
Legis is that why play.ogarul.tk is down?

**Comment by SharkFinPro** [comment]
Thanks to the noob, trydox who doesn't know how to make anything, but rather steal content from play.ogarul.tk, which was the reason due to the shut down!. I don't know will I open it back or not, but security will be buffen up, and no other clients other than play.ogarul.tk can access skins!. Legal actions is being taking over trydox for his illegal actions.

@LegitSoulja Posted that on stats.ogarul.tk

**Comment by Agarian** [comment]
what?

**Comment by Agarian** [comment]
oh

**Comment by fayizan** [comment]
WOW @Andrews54757  you are back..!!

**Comment by GetRektAgario** [comment]
Wait is it completed yet or more to come @Andrews54757

**Comment by Andrews54757** [comment]
Almost done

**Comment by GetRektAgario** [comment]
okay thanks so much it will help so much with my vps 👍

**Comment by GetRektAgario** [comment]
when you have finished will put a full version download?

**Comment by LegitSoulja** [comment]
@GetRektAgario normally, you will get an alert if there's an update, plus it'll be merged, so yes you'll be able to download the same was as normal. Be patient.

We all know @Andrews54757 has been gone for a while, and I'd like to ask what you been up to lately the past few weeks? Everyone missed you lol.

**Comment by Megabyte918** [comment]
Me and @LegitSoulja thought you died lol

**Comment by GetRektAgario** [comment]
Thanks @LegitSoulja

**Comment by GetRektAgario** [comment]
yey only one more thing :P

**Comment by Agarian** [comment]
God damnit...

**Comment by Agarian** [comment]
And that kids is why you don't use your phone for github.

**Comment by Agarian** [comment]
@Megabyte918 How did you fix linesplitting and virus throws so easily? And note while linesplit works, its still a little difficult to do it, if the mouse is in just the wrong spot, the linesplit doesn't stay straight =|

**Comment by LegitSoulja** [comment]
I could lines it without this code. But this fix made it ever better. There's a trick to a perfect line split :)

**Comment by Agarian** [comment]
i hope my recent commits didn't cause conflicts...

**Comment by Andrews54757** [comment]
its okay, I know command line.

**Comment by GetRektAgario** [comment]
@Andrews54757 how long do you think this project will take?

**Comment by fayizan** [comment]
omg this is a looongest PR I ever seen,How long this gonna take..?? sooo waiting eagerly.... :O

**Comment by firelightning13** [comment]
@fayizan No. The longest one was @MichaelLeeHobbs

**Comment by Andrews54757** [comment]
I've decided to use a Quadtree for ogarUL. See my project: https://github.com/AJS-development/QuadMap. Note I need help making the docs

**Comment by GetRektAgario** [comment]
@Andrews54757 but will you still continue this project?

**Comment by GhostShot3** [comment]
Too much commits

**Comment by GetRektAgario** [comment]
lol yeah

**Comment by GetRektAgario** [comment]
too confusing

**Comment by NatsuTheGreat** [comment]
>There's a trick to a perfect line split :)

Lets hear it.

**Comment by GetRektAgario** [comment]
@LegitSoulja yeah spill the beans :D

**Comment by LegitSoulja** [comment]
@NatsuTheGreat Mega never told you about it? I told him about it. It's very simple and easy. I used to line split from top to the bottom of the map like no worries. It was pretty cool.

@Megabyte918

**Comment by Agarian** [comment]
Lol i wanna know

**Comment by LegitSoulja** [comment]
If you haven't figured out, nor haven't understood how physics works then I'm sorry.

Anyone can determine not to split when you know for a fact a cell will hit one another which will mess up all angles of splitting.

**Comment by Megabyte918** [comment]
I'm not sure about the angle, if you're lucky it'll be changed to vertical and if that DOES happen your supposed to split every second (every half second works for me), but most of the time it will stay diagonal  and break the line.

**Comment by LegitSoulja** [comment]
That's why it's best to kindof do it diagonally, and not straight down, or up. You have to slant a little bit. 

I've master it. It's very easy, but it's something you'll have to practice to pack it down.

**Comment by Megabyte918** [comment]
How long does it take to make calcViewBox run in a child jesus christ

**Comment by LegitSoulja** [comment]
He's not only doing that.. I think he's also fixing lag issues. Didn't you read his last issue? Just stop bothering him :/

Good luck @Andrews54757 . I may or may not be back for a while. I wish you luck on this project, and I hope this project will still exist in the future if I do come back. This literally can be the best Ogar. Let your dreams come true. Don't rush,take your time! and make sure when you release things that it works. Do many many tests before making a PR, and don't make a PR and have people wait because then that'll be even more spam, and annoyance. 

This child process is a good thing, but I just don't know 100% about it. There's a lot of cons (Depending on your use for it). Like saying have each player have there own child process. 

You can do that, but I don't think it should be for every player but a cluster of players. Maybe 10-20 per process. Note that not everyone running servers wants Ogar cluttering up there CPU/GPU. Then OgarUnlimited new name would be something along the line as a 1 server use per machine which I KNOW that's the thing you want to do but eh, it'll take the point away of trying to host, or pretty much not being able to do anything once OgarUL is running. Just try to limit things, and also make a child config. It'll come in handle for some people.

Good luck AJS.

**Comment by GhostShot3** [comment]
@LegitSoulja You've been a good member, bye :(

**Comment by NatsuTheGreat** [comment]
Does anyone know why my console closes in a split second? I know it's because of an error, but I need to see it lmao...

**Comment by LegitSoulja** [comment]
Why don't you add a pause to the batch?

**Comment by NatsuTheGreat** [comment]
It was the Ogar UL console :/ But it'll try.

**Comment by NatsuTheGreat** [comment]
Thanks, LegitSoulja. It worked :)

**Comment by SharkFinPro** [comment]
When Is This gonna get finished?

**Comment by Agarian** [comment]
Never

**Comment by LegitSoulja** [comment]
@SharkFinPro when you retire, or when its time for your funeral, and even before that when aliens take over the world. Yea, it'll never be finished.

**Comment by Megabyte918** [comment]
Should this be closed? :/

**Comment by Agarian** [comment]
@LegitSoulja i had the idea for the chat cooldown to be based off the config "chatIntervalTime", because as of right now, it isn't optional.

**Comment by Agarian** [comment]
And i just remembered that tomorrow school starts :neutral_face:

**Comment by SharkFinPro** [comment]
@Agarian My school starts the day after labor day :/

**Comment by ItzLevvie** [comment]
My school starts in 2nd of September :P

**Comment by NatsuTheGreat** [comment]
@ItzLevvie When did it end?

**Comment by ItzLevvie** [comment]
15th of June

**Comment by NatsuTheGreat** [comment]
Okay, so that pretty fair.

**Comment by LegitSoulja** [comment]
@Agarian I've already added a cool down to the client aswell instead of letting the client handle it.

**Comment by LegitSoulja** [comment]
I just now have to make an automatic ban system for people using ddos tools, and vpns, and proxy uses. 

If someone get banned on purpose, we wouldn't want them coming back at all. 

There will be user registrations, so maybe you'll have to register to be able to chat, and play and etc because that'll give me more advantage who can access the site via accounts, and not by ip addresses. 

Many people can spoof there IP address, but then if there actually ip is leaked to an account that was registered with a ban ip that was spoofed then both ip's would be banned.

**Comment by WolfOGG** [comment]
Is this done ;-;?

**Comment by Agarian** [comment]
No :neutral_face:

**Comment by WolfOGG** [comment]
😔

**Comment by GhostShot3** [comment]
@Agarian  Hi

**Comment by AlexandriteErikParacelsus** [comment]
Jesus stop chatting on this PR

**Comment by LegitSoulja** [comment]
Gordon Ramsay needs to get back in the kitchen instead of chatting...

**Comment by GhostShot3** [comment]
@Andrews54757 Because you stopped the commits?

**Comment by Megabyte918** [comment]
Closing this for now...

**Comment by GhostShot3** [comment]
@Megabyte918 Why not put "On Hold" label instead of closing

**Comment by LegitSoulja** [comment]
No, this is done. There's no more updates. I think...

**Comment by GhostShot3** [comment]
it is missing
dfdfd

**Comment by LegitSoulja** [comment]
@GhostShot3 *sigh*, no comment..

**Comment by GhostShot3** [comment]
@LegitSoulja OK then.

**Comment by LegitSoulja** [comment]
@GhostShot3 why you removed your comment? Ok then? Look's like it's not if you removed your comment.

**Comment by GhostShot3** [comment]
Ok then²

**Comment by GhostShot3** [comment]
And I will not waste my time here.

**Pull request closed without merging**
