### PR TITLE
Bug413

### PR DESCRIPTION
**Pull request by MichaelLeeHobbs**
Fixes foodspawn and killall

I have read and agreed to the contributing guidelines

### CODE REVIEW

**Comment by MichaelLeeHobbs** [comment]
Man hound takes forever!

**Comment by Andrews54757** [comment]
no, i disabled it

**Comment by Megabyte918** [comment]
RIP hound

**Comment by firelightning13** [comment]
RIPRIP

**Comment by XtremePlayzCODE** [comment]
RIP hound

**Pull request merged**
