### PR TITLE
lol

### PR DESCRIPTION
**Pull request by Agarian**
I have read and agreed to the contributing guidelines

### CODE REVIEW

**Comment by Agarian** [comment]
these f*cks bought slitherio a long time ago but still!

**Comment by Megabyte918** [comment]
the did? I didn't even know

**Comment by Agarian** [comment]
lol imma close it anyway

**Comment by Megabyte918** [comment]
@Agarian go on discord

**Comment by ItzLevvie** [comment]
They've not even bought slither.io yet xD

**Comment by LegitSoulja** [comment]
Lol right. They haven't just yet.

**Pull request closed without merging**
