### PR TITLE
Try to fix #1209

### LINKED ISSUE #1209: Skins have correct name, but skin does not show up
sometimes when people have a skin, the skin does not show up and it is just the player color even though the skin name was spelled correctly. also happens with skin changer.

i think what the problem is for the skin changer are some names arent spelled correctly in randomskins.txt

### PR DESCRIPTION
**Pull request by XtremePlayzCODE**
I tried to fix #1209 (Skins have correct name, but skin does not show up)
This may fix only part of the issue however.

I have read and agreed to the contributing guidelines.

### CODE REVIEW

**Comment by Megabyte918** [comment]
Is this ready to be merged?

**Comment by XtremePlayzCODE** [comment]
Yes.

**Comment by XtremePlayzCODE** [comment]
Or atleast I think so.

**Comment by XtremePlayzCODE** [comment]
k thx

**Comment by Agarian** [comment]
@Megabyte918 I DID IT! I MADE SPECZOOM ACCOUNT FOR SPLITTING CELLS!

**Comment by Megabyte918** [comment]
@Agarian u did?! how?

**Comment by Agarian** [comment]
COME TO MY C9

**Comment by Agarian** [comment]
and discord

**Comment by Agarian** [comment]
@Megabyte918 Come on discord m8

**Comment by Agarian** [comment]
@Megabyte918

**Comment by SharkFinPro** [comment]
@Agarian I See the Ogar Server Beta =)

**Comment by Agarian** [comment]
wut

**Comment by XtremePlayzCODE** [comment]
lolwut

**Comment by Megabyte918** [comment]
im coming on discord

**Comment by XtremePlayzCODE** [comment]
im confused here

**Comment by SharkFinPro** [comment]
Can I have the discord chat link pleease....

**Comment by Megabyte918** [comment]
@SharkFinPro https://discord.gg/TxBhN

**Comment by Agarian** [comment]
@Megabyte918 where were u? You were online when i gave up on waiting...

**Pull request merged**
