### PR TITLE
New config and GhostShot3's changes

### PR DESCRIPTION
**Pull request by Agarian**
- Adds the changes @GhostShot3 wanted in #1320.
- Adds a config (`playerOldColors`) which, if set to 1, makes cells use Ogar's OLD/ORIGINAL colors. (tested, no bugs found)
- Makes the change command work more properly.

I have read and agreed to the contributing guidelines

### CODE REVIEW

**Comment by Agarian** [comment]
I WOLL MAKE ONE MORE CHANGE! Don't merge yet!

**Comment by NatsuTheGreat** [comment]
Yeah fix the fast that you left playerOldColors undefined in gameserver.ini :/

**Comment by Agarian** [comment]
Yeah i forgot it :neutral_face:

**Comment by Agarian** [comment]
Will make one last change!

**Comment by NatsuTheGreat** [comment]
I still don't see it XD

**Comment by Agarian** [comment]
https://github.com/AJS-development/Ogar-unlimited/pull/1337/commits/e5084295028be5b72be3c493df0d27583cd763cb

**Comment by NatsuTheGreat** [comment]
Oopsie daisy, I don't use OgarUL. I use my modified version. And you left it as ```playerOldColors``` I suggest making it ```playerOldColors = 0``` to avoid any bug with undefined.

**Comment by GhostShot3** [comment]
@Agarian Much better.

**Comment by GhostShot3** [comment]
@Agarian You're improving the performance of the skins in the game?

**Comment by Agarian** [comment]
what no

**Comment by GhostShot3** [comment]
@Agarian What are these other Commits

**Comment by GhostShot3** [comment]
@Agarian already understood

**Comment by GhostShot3** [comment]
@Agarian Leverages and gets the skins that are flashing.

**Comment by Agarian** [comment]
Skin flashing is the client

**Comment by GhostShot3** [comment]
@Agarian Ah its ok

**Comment by GhostShot3** [comment]
@Agarian I thought it was bug

**Comment by GhostShot3** [comment]
@Agarian No clonflits :)

**Comment by GhostShot3** [comment]
What is playerOldColors config ?

**Comment by Agarian** [comment]
Try it

**Comment by GhostShot3** [comment]
@Agarian Thx for Remake my pr

**Comment by LegitSoulja** [comment]
Skin flashing is the client? Really? Well shxt

**Comment by GhostShot3** [comment]
@LegitSoulja Yes is flashing :(

**Pull request merged**
