### PR TITLE
Small but annoying bug fix

### PR DESCRIPTION
**Pull request by Agarian**
Disallow bots to respawn when the **``kickbots [amount]``** is ran.

I have read and agreed to the contributing guidelines

### CODE REVIEW

**Comment by GhostShot3** [comment]
@Agarian Run not ran.

**Comment by NatsuTheGreat** [comment]
We're not in LA class, okay?

**Comment by GhostShot3** [comment]
@NatsuTheGreat who me ?

**Comment by NatsuTheGreat** [comment]
>@Agarian run not ran.

Yep.

**Comment by GhostShot3** [comment]
@NatsuTheGreat What is LA

**Comment by ItzLevvie** [comment]
^^ Probably stands for "Los Angeles" or something :P

**Comment by GhostShot3** [comment]
and why ?

**Comment by NatsuTheGreat** [comment]
@ItzLevvie No LMAO XD. I am talking about Language Arts/Writing class.

**Comment by Megabyte918** [comment]
Los Angeles class lol

**Comment by firelightning13** [comment]
Lol I don't think he got that reference (me either)

**Comment by Agarian** [comment]
I have algebra 2 in 9th grade :neutral_face:
Wish me luck

**Pull request merged**
