### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by Agarian**
Placement is a little odd, but it will do for now, i may put this with the `gamemode` command so it would be typed as `gamemode list`. For now, the command is **`gamemodes`**

- Collisions don't twitch or "twerk" ( #1285 ) nearly as much as before. (IDK if i messed up any of Megabyte's additions he made)
- Spectate zoom now accounts for splitting cells.
- Freeroam spectate speed it a little more matched to agar now.

I have read and agreed to the contributing guidelines

### CODE REVIEW

**Comment by Megabyte918** [comment]
Do you want this to be merged before or after Andrew comes back?

**Comment by Agarian** [comment]
idk =\
i can wait tho

**Comment by Andrews54757** [comment]
Kinda useless until the gamemode command is fixed, but oh well

**Comment by Agarian** [comment]
@Megabyte918 the improved spec code is here

**Comment by Megabyte918** [comment]
ready to be merged?

**Comment by Agarian** [comment]
yep i guess

**Comment by fayizan** [comment]
@Agarian Spectate is not working for me
screenshot_20

**Comment by Agarian** [comment]
huh?
shit

**Comment by Agarian** [comment]
lil i made a minor mistake and reverted this for nothing :disappointed:

**Comment by Agarian** [comment]
@fayizan get the latest version again please, it should work, as i tested it

**Comment by fayizan** [comment]
I tried it again but still getting this error when I click spectate
screenshot_21

**Comment by fayizan** [comment]
@Agarian  cool its working now,good job :+1: dude and thnk us soo much

**Pull request merged**
