### PR TITLE
Commeting fs sync functions

### PR DESCRIPTION
**Pull request by MichaelLeeHobbs**
After testing I have found that two of the fs.readSync and fs.writeSync are causing lag. Not all of the fs sync functions have been tested. Once I have tested them all I will work on removing the ones that are causing issues. This commit is commenting the sync functions and which ones cause issues.

### CODE REVIEW

**Comment by Agarian** [comment]
i dont think this should be merged. it may cause confilct with the "Big Update"

**Comment by MichaelLeeHobbs** [comment]
That's fine. My goal is to get the sync issues fixed this weekend. I'd also like to start getting some profiling going and see where some performance issues might be.

**Comment by Megabyte918** [comment]
All hail Michael

**Comment by firelightning13** [comment]
All hail Michael

**Pull request merged**
